### PR TITLE
Dham/periodic meshes

### PR DESCRIPTION
**Pull request by dham**
The periodic interval and rectangle meshes are created by unrolling circle, cylinder and torus meshes respectively. This PR changes the previous hand-coded parloops to instead use interpolation.

### CODE REVIEW

**Comment by ksagiyam** [comment]
https://github.com/firedrakeproject/firedrake/pull/3550 should fix most tests.

**Review by JDBetteridge — APPROVED** [review]

**Comment by JDBetteridge** [comment]
One test is still failing, also there seems to be a significant performance regression. Perhaps the runners are just a bit busy post meeting :thinking:

**Comment by ksagiyam** [comment]
Fixed.

**Review by ksagiyam — APPROVED** [review]

**Comment by JDBetteridge** [comment]
Woah woah woah! What about the performance regression!!! I'm disabling auto-merge until we see the CI run times 1hr28mins is _significantly_ longer than the usual ~45mins

**Comment by ksagiyam** [comment]
The latest CI ran fine in terms of time. Complex is still having issues.

**Comment by dham** [comment]
> The latest CI ran fine in terms of time. Complex is still having issues.

This is the failure:

```
2024-07-18T18:59:11.2911308Z ERROR tests/vertexonly/test_interpolation_from_parent.py::test_vector_function_interpolation_parallel[periodicrectangle-mesh-0-coords-VectorFunctionSpace(CG2)] - OSError: /__w/firedrake/firedrake_venv/.cache/pyop2/74/1406945cbcb02cfa0ef3f997d807fc.so: undefined symbol: catan2
```

Basically, we're calling `atan2` on complex-valued arguments and loopy is hence generating a call to a notional `catan2`, which doesn't exist. I will see if simply wrapping the relevant values in `real` does it.

**Review by ksagiyam — APPROVED** [review]

**Pull request merged**
