### PR TITLE
xfail coffee -O4 on hyperelasticity test

### PR DESCRIPTION
**Pull request by miklos1**
Fabio says coneoproject/COFFEE#72 fixes all outstanding COFFEE issues, but -O4 in the hyperelasticity test case will fail for now.

### CODE REVIEW

**Comment by wence-** [comment]
ZeroRemover.reschedule returns `None` in a bunch of cases where it should return a dict of some kind I think.

**Comment by miklos1** [comment]
I don't get it, but I guess you are saying this to Fabio.

**Comment by FabioLuporini** [comment]
I changed it to return an empty dict instead of None. This is returned when zeroremoval doesn't take place.

However, this was unrelated to this PR: the xfail is because the vectorizer still needs a little tweaking

**Comment by wence-** [comment]
Yes

**Pull request merged**
