### PR TITLE
Benney-Luke demo

### PR DESCRIPTION
**Pull request by wence-**
Cleaned up version of #426.

### CODE REVIEW

**Comment by wence-** [comment]
I think this is now good to go.  I've added a note (with reference to the COFFEE bug) in the script that we currently turn off kernel optimisation so that the simulation actually runs.  Do you want to add your email addresses to the contribution line or is it not a big issue?

**Comment by wence-** [comment]
If you like we could also acknowledge funding.

**Comment by wence-** [comment]
Merged and pushed out to the website.  The new demo can be seen at http://firedrakeproject.org/demos/benney_luke.py.html.  Thanks again.

**Comment by kalogirou** [comment]
Sorry, I was away from my office. Is it too late now or shall I give you the details for funding and email addresses?

**Comment by wence-** [comment]
If you feel that you'd like to explicitly mention a funding body and have contact emails in the demo, sure.  Otherwise no problem.

**Comment by kalogirou** [comment]
Also, I just noticed that some lines look longer online than in the version I had on my laptop, and in one case the equation is cut off.

**Comment by kalogirou** [comment]
Ok, how do we make the changes now? Shall I do them myself or give you the relevant information?

**Comment by wence-** [comment]
I'll open a new pull request for the line break changes, and if you send me the relevant details I'll add that too.

**Comment by kalogirou** [comment]
Thank you!

Can you please add the following right after the sentence "The work is based on...": 
The authors gratefully acknowledge funding from EPSRC grant no. EP/L025388/1 with a link to the Dutch Technology Foundation STW for the project “FastFEM: behavior of fast ships in waves”.

It would also be nice the have links on our the contributors names directing to their emails, which are: 
A.Kalogirou @ leeds.ac.uk
and 
O.Bokhove @ leeds.ac.uk

**Comment by kalogirou** [comment]
Regarding the line breaks, on my laptop all equations seem to fit in but on my desktop some expressions are cut off.. In any case, the changes should be as follows:
1. Eq. (1), line 3, each of the three brackets should be on different lines and aligned.
2. Same for Eq. (2).
3. Eq. (7) (right before the "Finaly, ..."), please align expressions for \eta and \phi on different lines.
4. In the coding part, at the definitions of the residuals Fphi_h, Feta, Fphi, could you please align the - (minus) at the beginning of the second lines with the = on the first lines to fit Feta into the screen (and for consistency)?

**Comment by wence-** [comment]
I've done this.  You can see the result of the changes at http://www.doc.ic.ac.uk/~lmitche1/benney_luke.py.html, hopefully everything is now fine.

**Comment by kalogirou** [comment]
It looks great, thank you very much!

**Comment by wence-** [comment]
Merged and online at http://firedrakeproject.org/demos/benney_luke.py.html

**Pull request merged**
