### PR TITLE
Assemble inverse

### PR DESCRIPTION
**Pull request by dham**
Working (except maybe on Mac!) and tested inverse assembly. Needs https://github.com/coneoproject/COFFEE/pull/35 to land.

### CODE REVIEW

**Comment by wence-** [comment]
If I understand things correctly, the firedrake_inverse.h header file is now unnecessary?

**Comment by wence-** [comment]
Yeah, doesn't work on Mac.  The magic incantation is an additional compiler flag passed in.  I will add it in PyOP2.

**Comment by wence-** [comment]
One thing I note.  Is it always guaranteed that the local tensor is symmetric, given that it's stored in row-major order, but lapack expects column-major?

**Comment by dham** [comment]
On the column-major front, transpose and inverse commute so it doesn't matter if your are row or column major.

**Pull request merged**
