### PR TITLE
Un-xfail COFFEE -O4 in hyperelasticity

### PR DESCRIPTION
**Pull request by miklos1**

### CODE REVIEW

**Comment by wence-** [comment]
Fabio should comment on which of these tests actually tests different things.  I don't recall which optimisation settings in coffee are now different

**Comment by miklos1** [comment]
Let me just call @FabioLuporini here.

**Comment by FabioLuporini** [comment]
At the moment O2==O3 because there's still a minor issue that I need to fix with the vectorizer (it's coming up, it's a matter of days). We should however test the whole range O0-O4 because they will soon differ.

**Comment by wence-** [comment]
OK, go ahead then.

**Pull request merged**
