### PR TITLE
Rckirby/install irksome

### PR DESCRIPTION
**Pull request by rckirby**
Allows firedrake-install to install Irksome.

### CODE REVIEW

**Comment by dham** [comment]
The merge commit passed, which is the important one. The one thing which is missing is that you should put `--install irksome` into the jenkinsfile install line so that Irksome installation is tested.

**Comment by wence-** [comment]
> The merge commit passed, which is the important one. The one thing which is missing is that you should put --install irksome into the jenkinsfile install line so that Irksome installation is tested.

Just did that.

**Comment by wence-** [comment]
> Just did that.

There was an error in the URL specification which I think I have fixed.

**Comment by wence-** [comment]
Thanks!

**Pull request merged**
