### PR TITLE
firedrake-update installs petsc4py if not yet installed

### PR DESCRIPTION
**Pull request by ksagiyam**
This PR is to let `firedrake-update` install `petsc4py` if not yet installed.

### CODE REVIEW

**Comment by ReubenHill** [comment]
Has something changed that necessitates this? I thought petsc4py was part of PETSc now?

**Comment by ksagiyam** [comment]
Firedrake still installs `petsc` and `petsc4py` separately. If `firedrake-install` fails somewhere after successfully installing `petsc`, `firedrake-update` can continue installation bypassing the expensive `petsc` installation, but currently this process fails to install `petsc4py`, as we assume that we already have `petsc4py` when we call `firedrake-update`. This PR attempts to fix this.

**Comment by connorjward** [comment]
Could this be made clear in a comment?

**Comment by ksagiyam** [comment]
Thanks. Added comments.

**Pull request merged**
