### PR TITLE
update setup.py to install all subpackages

### PR DESCRIPTION
**Pull request by JaroslavHron**
all subpackage has to be explicitly mentioned in setup to be installed - see #1477

### CODE REVIEW

**Comment by wence-** [comment]
Thanks. This looks right, I think. As an aside, is there a reason that you are doing the install this way (with prefix install) rather than using `firedrake-install`? The latter allows much easier updates of the installation (with `firedrake-update`), and isolates the python environment from any other packages.

**Comment by JaroslavHron** [comment]
this was issue I run into when setting up firedrake installation on our cluster using `spack` -https://spack.io/ - we use it for most of the other software installs, like fenics

it still has some rough corners and needs some cleanup - if anyone is interested see https://github.com/JaroslavHron/spack_repo

**Comment by wence-** [comment]
Thanks, this looks like the right change.

I note that tracking what options we might require for PETSc could be tricky, in #1474 I update firedrake-install show that `firedrake-install --show-petsc-configure-options` just prints the required options and exits.

**Comment by wence-** [comment]
Thanks!

**Pull request merged**
