### PR TITLE
Firedrake21 - recorded talk

### PR DESCRIPTION
**Pull request by sv2518**
Include information about recorded talks on webpage of the event.

### CODE REVIEW

**Comment by sv2518** [comment]
This only works if all videos are uploaded with "Firedrake '21" in their title, I assume that is correct?

**Comment by wence-** [comment]
Can one set up a vimeo "list" instead?

**Comment by sv2518** [comment]
Potentially, but I assume only David can do that, because he is the one who uploaded them.

**Comment by sv2518** [comment]
Okay, @dham, the alternative is that you generate something called a "showcase", which is basically a list, I think. They say "A showcase is a great way to distribute a collection of videos to any audience." Up to you. If you want to do that just send me the link to it and I can change the PR here.

**Pull request merged**
