### PR TITLE
Receives and sends for ensemble communicator

### PR DESCRIPTION
**Pull request by colinjcotter**
Adding blocking and non-blocking sends and receives for the Ensemble communicator.

(written by Wei Pan).

### CODE REVIEW

**Comment by ReubenHill** [comment]
For the uninformed like me, what's the problem this PR is solving?

**Comment by dham** [comment]
> For the uninformed like me, what's the problem this PR is solving?

It's the ability to send a whole Function from one ensemble member to another. Previously ensemble members could only send statistics to each other. This was always in the Ensemble API (hence the `NotImplementedError`s), it's just nobody had got around to the implementation.

**Review by wence- — CHANGES_REQUESTED** [review]
Very minor change, otherwise looks good, thanks.

**Comment by wence-** [comment]
Can you please fix the flake8 failures. Run `make lint` in the firedrake repo to see them. It should return no errors.

**Comment by whotookmyname** [comment]
Done. I've fixed the lint errors and added 'status' to 'recv'. Thanks.

**Comment by wence-** [comment]
I realised this would have problems for non-blocking send/receive of mixed functions (since in those cases the PETSc Vec and the Firedrake function do not share memory). The context manager in `irecv` would do the writeback before the request had completed.

I've pushed fixes for this (and a test). The interface has changed slightly, you now get back a list of requests from `isend` and `irecv` which you can wait on with `MPI.Request.waitall`.

**Comment by wence-** [comment]
Please check that things continue to work for you.

**Review by wence- — APPROVED** [review]

**Review by wence- — APPROVED** [review]

**Pull request merged**
