### PR TITLE
Pefarrell/hdf5file

### PR DESCRIPTION
**Pull request by wence-**
Supersedes #944 

- Only uses h5py for writing (avoiding horrible reference counting issues)

- Updates firedrake-install to build h5py from git (since this is the only sane way we can build with pip and require MPI support)

@pefarrell, @APaganini, please confirm this works for you.

### CODE REVIEW

**Comment by wence-** [comment]
After this is in, we can think about removing the DumbCheckpoint object, but that requires some downstream work in thetis and gusto to migrate (should not be hard).

**Comment by wence-** [comment]
Back-merged some fixes from master so this will hopefully pass CI.

**Comment by APaganini** [comment]
the test `test_write_read_parallel` (lines 85-87 in `test_hdf5file_checkpoint.py)
takes ages on my machine (maybe something is not properly set up in my installation).

The remaining tests pass without complaints.

**Comment by wence-** [comment]
what does "ages" mean?  That test executes `mpiexec -n 2 python ...` in a subprocess

**Comment by wence-** [comment]
Do all MPI programs take a long time?

**Comment by APaganini** [comment]
"ages" means that after 15 minutes I interrupt the test.

It might well be a problem of my installation. However, the test
`test_dumb_checkpoint.py` runs smoothly and also contains
a parallel test...

**Comment by wence-** [comment]
So all this does is open an hdf5 file in parallel, save, and load it.  Have you installed a parallel version of h5py?

**Comment by wence-** [comment]
Does the following take a similarly long amount of time:

```python
from firedrake import *

mesh = UnitSquareMesh(2, 2)
g = Function(V)

with HDF5File("foo.h5", mode="w", comm=mesh.comm) as f:
    f.write(g, "/solution")
    f.read(g, "/solution")
```

run with `mpiexec -n 2 python ...`

**Comment by APaganini** [comment]
I don't know if I had installed a parallel version of 'h5py'

Running what you suggested returns

```
(firedrakeAdjoint) $ mpiexec -n 2 python temp.py 
Traceback (most recent call last):
  File "temp.py", line 7, in <module>
    with HDF5File("foo.h5", mode="w", comm=mesh.comm) as f:
TypeError: __init__() got an unexpected keyword argument 'mode'
Traceback (most recent call last):
  File "temp.py", line 7, in <module>
    with HDF5File("foo.h5", mode="w", comm=mesh.comm) as f:
TypeError: __init__() got an unexpected keyword argument 'mode'
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

P.s: had to add the line
`V = FunctionSpace(mesh, "CG", 1)`
below the mesh contruction

**Comment by wence-** [comment]
Sorry, `file_mode=...`

**Comment by APaganini** [comment]
ok, now this runs fine

**Comment by wence-** [comment]
So can you run the `run_write_read` function from the test file in parallel fine?

**Comment by APaganini** [comment]
No, I meant that I

```
from firedrake import *

mesh = UnitSquareMesh(2, 2)
V = FunctionSpace(mesh, "CG", 1)
g = Function(V)

with HDF5File("foo.h5", file_mode="w", comm=mesh.comm) as f:
    f.write(g, "/solution")
    f.read(g, "/solution")
```

runs fine.

**Comment by wence-** [comment]
OK, so that works.  The next step is to figure out why the test was hanging.  To that end, I was suggesting running the test "on its own" in parallel.

**Comment by APaganini** [comment]
ok I'll try that.

**Comment by APaganini** [comment]
this
```
from firedrake import *
import numpy as np
import math

mesh = UnitSquareMesh(2, 2)
V = FunctionSpace(mesh, "CG", 1)
#g = Function(V)

dumpfile = str(("dump.h5"))

#V = FunctionSpace(mesh, fs, degree)

f = Function(V, name="f")
expr = Expression("x[0]*x[1]")
f.interpolate(expr)

g = Function(V, name="g")
expr = Expression("1+x[0]*x[1]")
g.interpolate(expr)

f2 = Function(V, name="f")
g2 = Function(V, name="g")

dumpfile = mesh.comm.bcast(dumpfile, root=0)

with HDF5File(dumpfile, "w", comm=mesh.comm) as h5:
    h5.write(f, "/solution")
    h5.read(f2, "/solution")

assert np.allclose(f.dat.data_ro, f2.dat.data_ro)

with HDF5File(dumpfile, "w", comm=mesh.comm) as h5:
    h5.write(f, "/solution", timestamp=math.pi)
    h5.write(g, "/solution", timestamp=0.1)
    h5.read(f2, "/solution", timestamp=math.pi)
    h5.read(g2, "/solution", timestamp=0.1)

    with g2.dat.vec as x, f2.dat.vec as y:
        assert x.max() > y.max()

assert np.allclose(f.dat.data_ro, f2.dat.data_ro)
```
fails with

```(firedrakeAdjoint) $ mpiexec -n 2 python temp2.py
Traceback (most recent call last):
  File "temp2.py", line 30, in <module>
    assert np.allclose(f.dat.data_ro, f2.dat.data_ro)
AssertionError
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

**Comment by wence-** [comment]
What about:
```python
import h5py
print h5py.get_config().mpi
print h5py.version.info
```

**Comment by APaganini** [comment]
```
In [1]: import h5py

In [2]: print h5py.get_config().mpi
False

In [3]: print h5py.version.info
Summary of the h5py configuration
---------------------------------

h5py    2.5.0
HDF5    1.8.12
Python  2.7.12 (default, Jun 29 2016, 14:05:02) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.11.2
```

**Comment by wence-** [comment]
Just before I go mad, are you running the `pefarrell/hdf5file` branch from firedrakeproject/firedrake, or from your clone?

**Comment by APaganini** [comment]
from `pefarrell/hd5file`; here is the proof
```(firedrakeAdjoint) (pefarrell/hdf5file *)$ git branch
  aldapa/hdf5file
  master
* pefarrell/hdf5file
```

**Comment by wence-** [comment]
what does `git show` say?

**Comment by APaganini** [comment]
```
(firedrakeAdjoint) (pefarrell/hdf5file *)$ git show
commit f18808744773c7ef522c9c3de01a2a0def9ca56e
Author: Patrick Farrell <patrick.farrell@maths.ox.ac.uk>
Date:   Sat Nov 26 16:50:32 2016 +0000

    Updates to HDF5File.

diff --git a/firedrake/checkpointing.py b/firedrake/checkpointing.py
index 1f75e9e..a353357 100644
--- a/firedrake/checkpointing.py
+++ b/firedrake/checkpointing.py
@@ -5,6 +5,7 @@ from firedrake import hdf5interface as h5i
 import firedrake
 import numpy as np
 import os
+import h5py
 
 
 __all__ = ["DumbCheckpoint", "HDF5File", "FILE_READ", "FILE_CREATE", "FILE_UPDATE"]
@@ -308,32 +309,16 @@ class HDF5File(object):
     This object can be used in a context manager (in which case it
     closes the file when the scope is exited).
 
-    .. note::
-
-       This object contains both a PETSc ``Viewer``, used for storing
-       and loading :class:`~.Function` data, and an :class:`h5py:File`
-       opened on the same file handle.  *DO NOT* call
```

**Comment by wence-** [comment]
OK, that is not this branch.  For which `git show` is:

```
commit 5bd250f1bf1667b09a3371536e1e428f187247c5
Merge: 837058c ed05e72
Author: Lawrence Mitchell <lawrence.mitchell@imperial.ac.uk>
Date:   Mon Dec 5 11:29:33 2016 +0000

    Merge branch 'master' into pefarrell/hdf5file
```

Note that I do not have write access to your fork, therefore I pulled your and patrick's changes into the upstream firedrake repo, and then made some more changes on top of that.

**Comment by APaganini** [comment]
oh... so shall I call `firedrake/bin/firedrake-update`?
Shall I switch to the master branch before doing so?

**Comment by wence-** [comment]
You'll need to do something like the following:

```
git checkout master
git branch -d pefarrell/hdf5file
git fetch -p origin
git checkout -b pefarrell/hdf5file origin/pefarrell/hdf5file
```
And then run `firedrake-update`.

**Comment by APaganini** [comment]
`firedrake-update` terminated with

```Installing h5py

Traceback (most recent call last):
  File "../bin/firedrake-update", line 1287, in <module>
    build_and_install_h5py()
  File "../bin/firedrake-update", line 683, in build_and_install_h5py
    os.rmdir("h5py-2.5.0")
OSError: [Errno 66] Directory not empty: 'h5py-2.5.0'```

This is most likely a mac issue...

**Comment by wence-** [comment]
Oh, that's presumably because `rmdir` doesn't remove non-empty directories.  I'll change it to use `shutil.rmtree`.

**Comment by wence-** [comment]
Please try running `firedrake-update` again.  I think I fixed this.

**Comment by APaganini** [comment]
now it complains about libadjoint

```
Successfully installed firedrake
Updating the git repository for libadjoint
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> apaganini/dockeradjoint

Traceback (most recent call last):
  File "../bin/firedrake-update", line 1303, in <module>
    build_and_install_adjoint()
  File "../bin/firedrake-update", line 795, in build_and_install_adjoint
    git_update(package, adjoint_deps[package])
  File "../bin/firedrake-update", line 497, in git_update
    check_call(["git", "pull"])
  File "../bin/firedrake-update", line 342, in check_call
    subprocess.check_call(arguments, env=env)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'pull']' returned non-zero exit status 1
```

**Comment by dham** [comment]
That message indicates that you are working on a local branch of libadjoint
which you have never pushed. Push the branch and run firedrake-update again.

Regards,

David

**Comment by wence-** [comment]
This *still* results in errors in `test_attributes` for me.  I now think it is an h5py bug, so I will report upstream.

**Comment by APaganini** [comment]
Thank you David. Now the error I get is

```
Configuring libadjoint for virtualenv installation in /Volumes/Scratch/Users/paalbert/Documents/FIREDRAKE/firedrakeAdjoint
CMake Error: The current CMakeCache.txt directory /Volumes/Scratch/Users/paalbert/Documents/FIREDRAKE/firedrakeAdjoint/src/libadjoint/CMakeCache.txt is different than the directory /home/fenics/shared/libadjoint where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
Traceback (most recent call last):
  File "../bin/firedrake-update", line 1305, in <module>
    build_and_install_adjoint()
  File "../bin/firedrake-update", line 826, in build_and_install_adjoint
    check_call(["cmake", "-DCMAKE_INSTALL_PREFIX=%s" % os.environ["VIRTUAL_ENV"], ".."], env=env)
  File "../bin/firedrake-update", line 342, in check_call
    subprocess.check_call(arguments, env=env)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_INSTALL_PREFIX=/Volumes/Scratch/Users/paalbert/Documents/FIREDRAKE/firedrakeAdjoint', '..']' returned non-zero exit status 1
```

**Comment by wence-** [comment]
`git clean -fdx` in `src/libadjoint/` I think.

**Comment by wence-** [comment]
I think I fixed the h5py issue.  We needed to call `h5py.File.close` on the internal h5py File, rather than just doing `del self._h5file`.

**Comment by APaganini** [comment]
yuppie, everything works now, many thanks

```
(firedrakeAdjoint) (pefarrell/hdf5file)$ py.test test_hdf5file_checkpoint.py 
=============================== test session starts ===============================
platform darwin -- Python 2.7.12, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
benchmark: 3.0.0 (defaults: timer=time.time disable_gc=False min_rounds=5 min_time=5.00us max_time=1.00s calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Volumes/Scratch/Users/paalbert/Documents/FIREDRAKE/firedrakeAdjoint/src/firedrake, inifile: 
plugins: benchmark-3.0.0, xdist-1.15.0
collected 17 items 

test_hdf5file_checkpoint.py .................

=========================== 17 passed in 57.02 seconds ============================
```

**Pull request merged**
