### PR TITLE
Use correct PETSc API to create global vertex numbering

### PR DESCRIPTION
**Pull request by miklos1**
Meant to fix issue #429.

Requires new binding to be merged into petsc4py.

### CODE REVIEW

**Comment by wence-** [comment]
Fine, once the petsc4py changes land.

**Comment by kynan** [comment]
I can believe that.

**Comment by miklos1** [comment]
New binding is in petsc4py `master` and `maint`. We need to update `firedrake` branch in petsc4py.

**Comment by wence-** [comment]
Done, and done.

**Pull request merged**
