### PR TITLE
Wence/fix/mumps fails

### PR DESCRIPTION
**Pull request by wence-**
Catches some places where we were asking mumps to invert either a singular operator or a saddle-point system (and the pivoting was not working well).

### CODE REVIEW

**Comment by ksagiyam** [comment]
I just tested on my local computer, but `test_star_pc` still fails even after making the operator non-singular. `test_manifolds` now looks fine.

**Comment by wence-** [comment]
> I just tested on my local computer, but `test_star_pc` still fails even after making the operator non-singular. `test_manifolds` now looks fine.

It might be that I didn't actually make it non-singular.

**Comment by ScottMacLachlan** [comment]
> > I just tested on my local computer, but `test_star_pc` still fails even after making the operator non-singular. `test_manifolds` now looks fine.
> 
> It might be that I didn't actually make it non-singular.

I think that's the wrong sign...

**Comment by ksagiyam** [comment]
It fails even if I further add `inner(z, v) * dx` to `a`. Actually the following is the MFE using `mat_mumps_icntl_7": 1`:
```
from firedrake import *


mesh = UnitSquareMesh(1, 1)
V = FunctionSpace(mesh, "DG", 0)

u = TrialFunction(V)
v = TestFunction(V)

a = inner(u, v) * dx
L = conj(v) * dx
up = Function(V)

params = {'mat_mumps_icntl_7': 1,
          'mat_mumps_icntl_24': 1,
          'ksp_view': None,
          'ksp_converged_reason': None}
solve(a == L, up, solver_parameters=params)

print(up.dat.data)
```

**Comment by ScottMacLachlan** [comment]
That's a strange failure, Koki - isn't MUMPS failing to factor a 2x2 diagonal matrix in that case?

Here's my big concern: the (original) failing test in `test_star_pc.py` is just a Q2-Q1 Stokes discretization - that's about as simple a saddle-point system as you'd expect to see (albeit with a 1-dimensional singularity).  Shouldn't we know solver parameters to robustly handle this case?

**Comment by ksagiyam** [comment]
Yes, and this error magically disappears if I use 'mat_mumps_icntl_7': 3.

I think we are using good solver parameters in `test_star_pc.py`, but we use `mumps` at the coarsest level, which is causing the error.

**Comment by wence-** [comment]
> That's a strange failure, Koki - isn't MUMPS failing to factor a 2x2 diagonal matrix in that case?

This sounds like a bug one should send upstream, because I can't believe that something isn't broken.

**Comment by wence-** [comment]
The fact that @ksagiyam writes `conj(v)*dx` makes me wonder if the Firedrake is installed in complex-mode, but still...

**Comment by ScottMacLachlan** [comment]
> > That's a strange failure, Koki - isn't MUMPS failing to factor a 2x2 diagonal matrix in that case?
> 
> This sounds like a bug one should send upstream, because I can't believe that something isn't broken.

That seems like a reasonable conclusion to me.

While I'm staring at this, though, is there a reason to try and pin `mat_mumps_icntl_7` manually?  From the MUMPS manual, their default would be a value of 7, which sets off some internal logic about which choice to use.  To my reading, PETSc over-rides that with a default of 0, to use AMD.  Does `'mat_mumps_icntl_7':7` DTRT here?

**Comment by wence-** [comment]
> While I'm staring at this, though, is there a reason to try and pin `mat_mumps_icntl_7` manually?

I have definitely cargo-culted any MUMPS options that appear in tests or elsewhere in Firedrake...

**Comment by ksagiyam** [comment]
I use real mode.

I modified `ksp/tests/ex2.c`, and was able to reproduced the problem. Does this MFE look fine?

```
#include <petscksp.h>
#include <petscvec.h>

int main(int argc,char **args)
{
  Mat            C;
  PetscErrorCode ierr;
  PetscInt       N = 2,rowidx,colidx;
  Vec            u,b;
  KSP            ksp;
  PetscMPIInt    rank,size;
  PetscScalar    v;
  PetscScalar   *a;

  ierr = PetscInitialize(&argc,&args,(char*)0,"");if (ierr) return ierr;
  ierr = MPI_Comm_rank(PETSC_COMM_WORLD,&rank);CHKERRMPI(ierr);
  ierr = MPI_Comm_size(PETSC_COMM_WORLD,&size);CHKERRMPI(ierr);

  /* create stiffness matrix C = [1 0; 0 1] */
  ierr = MatCreate(PETSC_COMM_WORLD,&C);CHKERRQ(ierr);
  ierr = MatSetSizes(C,PETSC_DECIDE,PETSC_DECIDE,N,N);CHKERRQ(ierr);
  ierr = MatSetFromOptions(C);CHKERRQ(ierr);
  ierr = MatSetUp(C);CHKERRQ(ierr);
  if (!rank) {
    rowidx = 0; colidx = 0; v = 1.0;
    ierr   = MatSetValues(C,1,&rowidx,1,&colidx,&v,INSERT_VALUES);CHKERRQ(ierr);

    rowidx = 1; colidx = 1; v = 1.0;
    ierr   = MatSetValues(C,1,&rowidx,1,&colidx,&v,INSERT_VALUES);CHKERRQ(ierr);
  }
  ierr = MatAssemblyBegin(C,MAT_FINAL_ASSEMBLY);CHKERRQ(ierr);
  ierr = MatAssemblyEnd(C,MAT_FINAL_ASSEMBLY);CHKERRQ(ierr);

  /* create right hand side and solution */
  ierr = VecCreate(PETSC_COMM_WORLD,&u);CHKERRQ(ierr);
  ierr = VecSetSizes(u,PETSC_DECIDE,N);CHKERRQ(ierr);
  ierr = VecSetFromOptions(u);CHKERRQ(ierr);
  ierr = VecDuplicate(u,&b);CHKERRQ(ierr);
  ierr = VecSet(u,0.0);CHKERRQ(ierr);
  ierr = VecSet(b,1.0);CHKERRQ(ierr);

  /* check initial values: [0., 0.] */
  ierr = PetscMalloc1(N, &a);CHKERRQ(ierr);
  ierr = VecGetArray(u, &a);CHKERRQ(ierr);
  ierr = PetscPrintf(PETSC_COMM_SELF, "u = [%g, %g]\n", a[0], a[1]);CHKERRQ(ierr);
  ierr = VecRestoreArray(u, &a);CHKERRQ(ierr);

  /* solve linear system C*u = b */
  ierr = KSPCreate(PETSC_COMM_WORLD,&ksp);CHKERRQ(ierr);
  ierr = KSPSetOperators(ksp,C,C);CHKERRQ(ierr);
  ierr = KSPSetFromOptions(ksp);CHKERRQ(ierr);
  ierr = KSPSolve(ksp,b,u);CHKERRQ(ierr);

  /* check computed values: expecting [1., 1.] */
  ierr = VecGetArray(u, &a);CHKERRQ(ierr);
  ierr = PetscPrintf(PETSC_COMM_SELF, "u = [%g, %g]\n", a[0], a[1]);CHKERRQ(ierr);
  ierr = VecRestoreArray(u, &a);CHKERRQ(ierr);
  ierr = PetscFree(a);CHKERRQ(ierr);

  ierr = KSPDestroy(&ksp);CHKERRQ(ierr);
  ierr = VecDestroy(&u);CHKERRQ(ierr);
  ierr = VecDestroy(&b);CHKERRQ(ierr);
  ierr = MatDestroy(&C);CHKERRQ(ierr);
  ierr = PetscFinalize();
  return ierr;
}
```

`mpiexec -n 1 ./ex999 -ksp_type preonly -pc_type lu -pc_factor_mat_solver_type mumps  -mat_mumps_icntl_7 1`
prints `u = [inf., inf.]`

`mpiexec -n 1 ./ex999 -ksp_type preonly -pc_type lu -pc_factor_mat_solver_type mumps  -mat_mumps_icntl_7 3`
prints `u = [1., 1.]`

**Comment by wence-** [comment]
That looks reasonably minimal.

**Comment by ksagiyam** [comment]
Created an issue: https://gitlab.com/petsc/petsc/-/issues/894

**Comment by sv2518** [comment]
@ScottMacLachlan mentioned in Slack that the demo qg_1layer was failing at some point as well. The demo is also failing on our sprint branch here https://jenkins.ese.ic.ac.uk/blue/organizations/jenkins/firedrake/detail/PR-2038/19/pipeline/162. I cannot see MUMPS being used in there, does that mean the demo failure is a separate issue?

**Comment by ksagiyam** [comment]
That demo at least passes on my local computer, where `test_star_pc` fails.

**Comment by knepley** [comment]
Pierre thinks this may not be MUMPS, but instead https://gitlab.com/petsc/petsc/-/merge_requests/3739 .The MUMPS problem seems to be a bad permutation array, which is exactly what this MR Is futzing with.

**Pull request merged**
