### PR TITLE
Implement integration of marked cell subdomains

### PR DESCRIPTION
**Pull request by wence-**
Requires that the plex provides useful Cell Sets label.

### CODE REVIEW

**Comment by miklos1** [comment]
This might not work for extruded, does it?

**Comment by wence-** [comment]
I think so.  Iteration always happens over the base mesh cell_set so now it just happens over a subset instead.  That's probably what one wants?

**Comment by miklos1** [comment]
Some of the implementation of extrusion is horrible. IIRC iterating over an extruded subset will either iterate only over the selected base cells, or the selected columns, depending on whether the par_loop arguments have some property.

**Comment by wence-** [comment]
OK, minimal testing indicates this works for extruded meshes too.

**Comment by wence-** [comment]
Now with tests.

**Comment by wence-** [comment]
Hopefully now with working.

**Pull request merged**
