### PR TITLE
Disable documentation build

### PR DESCRIPTION
**Pull request by dham**
Documentation build is currently failing. Disable it to enable docker container build.

### CODE REVIEW

**Comment by wence-** [comment]
It fails due to the issue reported at mcmtroffaes/sphinxcontrib-bibtex#229.

**Review by wence- — APPROVED** [review]

**Comment by ReubenHill** [comment]
Following the issue train above it looks like updating `sphinxcontrib-bibtex` to [2.1.4](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/releases/tag/2.1.4) ought to fix the issue?

**Comment by dham** [comment]
> Following the issue train above it looks like updating `sphinxcontrib-bibtex` to [2.1.4](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/releases/tag/2.1.4) ought to fix the issue?

Yes, and that ought to be automatic. I'm waiting on the current master build to see if this is just fixed.

**Comment by dham** [comment]
Upstream fix has landed. this is no longer needed.

**Pull request closed without merging**
