### PR TITLE
OpenCascadeMeshHierarchy in Complex mode

### PR DESCRIPTION
**Pull request by benSepanski**
I had to cast some coordinates to real values in order for `OpenCascadeMeshHierarchy` to run in complex mode.

### CODE REVIEW

**Comment by ReubenHill** [comment]
Is there a simple test that could be added to demonstrate what this fixes? I'm a little surprised this didn't get caught in the complex sprint.

**Comment by benSepanski** [comment]
The [opencascade_poisson](https://github.com/firedrakeproject/firedrake/blob/master/tests/multigrid/test_opencascade_poisson.py) test fails for me (after installing firedrake with `firedrake-install --complex --opencascade`) with the following error:
```
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/bmsepan/fd_projs/firedrake/src/firedrake, configfile: setup.cfg
plugins: forked-1.3.0, xdist-2.2.0
collected 6 items

test_opencascade_poisson.py F

=================================== FAILURES ===================================
____________________ test_opencascade_poisson[stepdata0-1] _____________________

stepdata = ('/home/bmsepan/fd_projs/firedrake/src/firedrake/tests/multigrid/../meshes/cylinder.step', 20)
order = 1

    def test_opencascade_poisson(stepdata, order):
        (stepfile, h) = stepdata
        try:
>           mh = OpenCascadeMeshHierarchy(stepfile, element_size=h, levels=2, order=order, cache=False, verbose=True)

test_opencascade_poisson.py:22: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../firedrake/mg/opencascade_mh.py:41: in OpenCascadeMeshHierarchy
    project_to_cad(mesh, cad)
../../firedrake/mg/opencascade_mh.py:160: in project_mesh_to_cad_3d
    pt = gp_Pnt(*coorddata[node, :])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = class<'gp_Pnt'>
args = ((18.85274008567277+0j), (7.53815021988703e-14+0j), 0j)

    def __init__(self, *args):
        r"""
        * Creates a point with zero coordinates.
    
        :rtype: None
        * Creates a point from a XYZ object.
    
        :param Coord:
        :type Coord: gp_XYZ
        :rtype: None
        * Creates a point with its 3 cartesian's coordinates : Xp, Yp, Zp.
    
        :param Xp:
        :type Xp: float
        :param Yp:
        :type Yp: float
        :param Zp:
        :type Zp: float
        :rtype: None
    
        """
>       _gp.gp_Pnt_swiginit(self, _gp.new_gp_Pnt(*args))
E       TypeError: in method 'new_gp_Pnt', argument 1 of type 'Standard_Real'
E       Additional information:
E       Wrong number or type of arguments for overloaded function 'new_gp_Pnt'.
E         Possible C/C++ prototypes are:
E           gp_Pnt::gp_Pnt()
E           gp_Pnt::gp_Pnt(gp_XYZ const &)
E           gp_Pnt::gp_Pnt(Standard_Real const,Standard_Real const,Standard_Real const)

../../../../lib/python3.8/site-packages/OCC/Core/gp.py:1906: TypeError
----------------------------- Captured stdout call -----------------------------
Report : 3 unknown entities
Info    : Running 'gmsh -3 /home/bmsepan/fd_projs/firedrake/src/firedrake/tests/multigrid/../meshes/coarse-cylinder.geo' [Gmsh 4.4.1, 1 node, max. 1 thread]
Info    : Started on Mon Jan 25 12:14:18 2021
Info    : Reading '/home/bmsepan/fd_projs/firedrake/src/firedrake/tests/multigrid/../meshes/coarse-cylinder.geo'...
Report : 3 unknown entities.
Info    :  - Label 'Shapes/Part 1' (3D)
Info    : Done reading '/home/bmsepan/fd_projs/firedrake/src/firedrake/tests/multigrid/../meshes/coarse-cylinder.geo'
Info    : Meshing 1D...
Info    : Meshing curve 1 (Circle)
Info    : Meshing curve 2 (Circle)
Info    : Meshing curve 3 (BSpline)
Info    : Done meshing 1D (0.0010469 s)
Info    : Meshing 2D...
Info    : Meshing surface 1 (Plane, Delaunay)
Info    : Meshing surface 2 (Plane, Delaunay)
Info    : Meshing surface 3 (Unknown, MeshAdapt)
Info    : Done meshing 2D (0.0073891 s)
Info    : Meshing 3D...
Info    : 3D Meshing 1 volumes with 1 connected components
Info    : Tetrahedrization of 44 points in 0.0006378 seconds
Info    : Reconstructing mesh...
Info    :  - Creating surface mesh
Info    :  - Identifying boundary edges
Info    :  - Recovering boundary
Info    :  - Added 1 Steiner point
Info    : Done reconstructing mesh (0.0042944 s)
Info    : Found region 1
Info    : 0 points created - worst tet radius 0.758014 (points removed 0 0)
Info    : 3D point insertion terminated (37 points created):
Info    :  - 0 Delaunay cavities modified for star shapeness
Info    :  - 0 points could not be inserted
Info    :  - 74 tetrahedra created in 3.93e-05 sec. (1882951 tets/s)
Info    : Done meshing 3D (0.0125358 s)
Info    : Optimizing 3D mesh...
Info    : Optimizing volume 1
Info    : Optimization starts (volume = 34571.8) with worst = 0.419565 / average = 0.668169:
Info    : 0.00 < quality < 0.10 :         0 elements
Info    : 0.10 < quality < 0.20 :         0 elements
Info    : 0.20 < quality < 0.30 :         0 elements
Info    : 0.30 < quality < 0.40 :         0 elements
Info    : 0.40 < quality < 0.50 :         8 elements
Info    : 0.50 < quality < 0.60 :         2 elements
Info    : 0.60 < quality < 0.70 :        22 elements
Info    : 0.70 < quality < 0.80 :        42 elements
Info    : 0.80 < quality < 0.90 :         0 elements
Info    : 0.90 < quality < 1.00 :         0 elements
Info    : No ill-shaped tets in the mesh :-)
Info    : 0.00 < quality < 0.10 :         0 elements
Info    : 0.10 < quality < 0.20 :         0 elements
Info    : 0.20 < quality < 0.30 :         0 elements
Info    : 0.30 < quality < 0.40 :         0 elements
Info    : 0.40 < quality < 0.50 :         8 elements
Info    : 0.50 < quality < 0.60 :         2 elements
Info    : 0.60 < quality < 0.70 :        22 elements
Info    : 0.70 < quality < 0.80 :        42 elements
Info    : 0.80 < quality < 0.90 :         0 elements
Info    : 0.90 < quality < 1.00 :         0 elements
Info    : Done optimizing 3D mesh (0.0002086 s)
Info    : 37 vertices 167 elements
Info    : Writing '/home/bmsepan/fd_projs/firedrake/src/firedrake/tests/multigrid/../meshes/coarse-cylinder.msh'...
Info    : Done writing '/home/bmsepan/fd_projs/firedrake/src/firedrake/tests/multigrid/../meshes/coarse-cylinder.msh'
Info    : Stopped on Mon Jan 25 12:14:18 2021
=========================== short test summary info ============================
FAILED test_opencascade_poisson.py::test_opencascade_poisson[stepdata0-1] - T...
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
============================== 1 failed in 0.77s ===============================
```
After adding in the casts to real, this test passes for me.

**Review by dham — CHANGES_REQUESTED** [review]
Is this tested somewhere?

**Comment by wence-** [comment]
The opencascade stuff is presently not tested on Jenkins, to make it happen, we need to add

`liboce-ocaf-dev`, and `swig` to the `firedrake.env` dockerfile, and add `--opencascade` to firedrake-install.

**Comment by wence-** [comment]
> The opencascade stuff is presently not tested on Jenkins, to make it happen, we need to add
> 
> `liboce-ocaf-dev`, and `swig` to the `firedrake.env` dockerfile (so that we can build with opencascade on jenkins), done as #1970.
> 
> Once #1970 is merged, we can add `--opencascade` to the `firedrake-install` line in the `Jenkinsfile` and rebase on top of master.
> 
> Presently Jenkins is broken so we can't push the docker stuff through yet.

We have merged #1970. So tomorrow (probably) the docker file will contain the opencascade dependencies. So can you add `--opencascade` to the firedrake-install line in this branch and push (having rebased on top of master)? We can advise on how to do this if things don't make sense.

**Comment by benSepanski** [comment]
Alrighty, I've rebased and added `--opencascade` to the Jenkinsfile

**Comment by wence-** [comment]
Ah, this is annoying, since your branch is from outside the firedrake organisation repository, the tests ran with the Jenkinsfile from our side (not yours) so not with the changes. I'm going to cross my fingers and hope it all works if I merge...

**Review by wence- — APPROVED** [review]

**Comment by wence-** [comment]
The builders hung on this. So I am going to revert this merge for now.

**Pull request merged**
