### PR TITLE
Add recursivenodes requirement

### PR DESCRIPTION
**Pull request by pbrubeck**
# Description

https://github.com/firedrakeproject/fiat/pull/46 has been merged, but we forgot to add this requirement to firedrake.

### CODE REVIEW

**Comment by wence-** [comment]
Surely fiat should require it

**Review by rckirby — APPROVED** [review]

**Review by dham — CHANGES_REQUESTED** [review]
As @wence- says, this should go into FIAT, not Firedrake.

**Comment by pbrubeck** [comment]
It's already in FIAT. Firedrake CI would complain if I don't put it here.

**Comment by pbrubeck** [comment]
Closing in favour of  https://github.com/firedrakeproject/firedrake/pull/3219

**Pull request closed without merging**
