### PR TITLE
Fix complex merge test mistakes

### PR DESCRIPTION
**Pull request by ReubenHill**

### CODE REVIEW

**Comment by ksagiyam** [comment]
It seems it's not broken anymore. Maybe just update this line `problem = LinearVariationalProblem(u*v*dx, 2*v*dx, self.uh)` in `NonePC` class for complex for consistency?

**Comment by djanekovic** [comment]
Hmm, this is weird because this test fails for me when I just remove skipif decorator, I just tried it locally. Why did the test pass on Jenkins?

**Comment by ReubenHill** [comment]
It fails for me too in real mode. I presume it's a test that's meant to run at a particular time?

**Comment by ReubenHill** [comment]
@ksagiyam see 1e3deb64ecbfa18be7a747677fc374cf41b24ccc - hopefully I got this correct.

**Comment by ksagiyam** [comment]
I can not reproduce it locally on my Ubuntu. @djanekovic and @ReubenHill What system do you run Firedrake on?

**Comment by djanekovic** [comment]
Locally I am running firedrake on Debian. I agree that the commit 1e3deb6 fixed the problem but I am wondering why the test passed on Jenkins when it was obviously broken. I looked the log for 3bcbeb9 build and you can clearly see that Jenkins ran the test and it passed where it should fail with ArityMismatch.
```
[2020-10-14T20:00:40.014Z] tests/regression/test_appctx_cleanup.py::test_appctx_cleanup 
... 
[2020-10-14T20:00:44.150Z] [gw2] [ 57%] PASSED tests/regression/test_appctx_cleanup.py::test_appctx_cleanup
```

**Comment by ReubenHill** [comment]
macos here - if memory serves the test crashed rather than failed for me.

**Comment by ksagiyam** [comment]
If I run this test with `-s` without 1e3deb6, I can actually see the `ArityMismatch` error, but the test is still regarded as passed.  I think this is the problem. With 1e3deb6, the test passes without any error.

**Comment by ReubenHill** [comment]
Weirdly `tests/regression/test_aw.py::test_aw[conforming]` fails on Jenkins on the complex PR merge test of 1e3deb6.

**Comment by sv2518** [comment]
The test fails also in the PR #1884

**Review by wence- — APPROVED** [review]
I think the changes are fine. Are we happy with the testing situation on jenkins?

**Pull request merged**
