### PR TITLE
save cubed-sphere radius

### PR DESCRIPTION
**Pull request by dorugeber**
Extending 2092c15, and minor variable rename

### CODE REVIEW

**Comment by dorugeber** [comment]
In the mg code, Lawrence is using the attribute to work out which mesh he's on, so you would need to find another way to do that.

**Comment by miklos1** [comment]
OK, then.

**Comment by wence-** [comment]
I think that different name is only being used to compute `gdim`.

**Comment by dorugeber** [comment]
Feel free to fixup.

**Pull request merged**
