### PR TITLE
Merge current master into pointwise-adjoint-operator

### PR DESCRIPTION
**Pull request by inducer**
@nbouziani I don't know if this is desired, but this is a straightforward merge of master into your branch. The only conflict was in `Jenkinsfile`, and the resolution appeared simple to me.

We need this in order to make progress on our nonlocal operator work, so that we can use the post-loopy-print state.

cc @rckirby

### CODE REVIEW

**Comment by nbouziani** [comment]
Thanks for the update @inducer! Yes merging master is desired (note that the PyOP2/Tsfc branch will also need to merge master to account for the loopy sprint).

However, it seems that the recent changes in `assemble` have broken the assembly of external operators. So this will need to be fixed for merging master. My understanding is that it is just a matter of adapting the way external operator are taken into account in assemble to the recent changes introduced by @connorjward.

Have your tested the nonlocal operator after having merged master?

**Comment by inducer** [comment]
> Have your tested the nonlocal operator after having merged master?

I wasn't yet able to.

**Comment by nbouziani** [comment]
> Thanks for the update @inducer! Yes merging master is desired (note that the PyOP2/Tsfc branch will also need to merge master to account for the loopy sprint).
> 
> However, it seems that the recent changes in `assemble` have broken the assembly of external operators. So this will need to be fixed for merging master. My understanding is that it is just a matter of adapting the way external operator are taken into account in assemble to the recent changes introduced by @connorjward.
> 
> Have your tested the nonlocal operator after having merged master?

I have merged master into my branch and fixed the assembly issue.

**Comment by inducer** [comment]
Thanks, and thanks for letting us know!

**Pull request closed without merging**
