### PR TITLE
Petsc updates

### PR DESCRIPTION
**Pull request by wence-**
These changes are necessary to come up to date with current PETSc master.

### CODE REVIEW

**Comment by wence-** [comment]
I also moved `dmplex.pxi` to `firedrakedmplex.pxi` so that cython annotating `dmplex.pyx` works.  Having done this, I noticed that there were some minor type annotation issues that I then fixed.

**Comment by miklos1** [comment]
I don't like the name `firedrakedmplex.pxi`, but otherwise the change is fine.

**Comment by wence-** [comment]
Any better suggestions?  `dmplexinc.pxi` ?

**Comment by miklos1** [comment]
I'm okay with `dmplexinc.pxi`.

**Comment by wence-** [comment]
OK, I've done that.  Just testing the petsc branches.

**Comment by wence-** [comment]
Failing due to petsc bug reported upstream.

**Comment by wence-** [comment]
PETSc fixes have landed.  Testing again.

**Comment by wence-** [comment]
OK, we're working again with upstream petsc.  Comments?

**Comment by wence-** [comment]
In particular, @mlange05, the way we determine boundary ids had to change because now the plex doesn't maintain all boundary ids as labels on all processes.

**Comment by miklos1** [comment]
I think this is all right.

**Comment by mlange05** [comment]
Yes, this looks good. The fix for maintaining boundary IDs looks good too, although we should probably fix this upstream at some point by doing the `allreduce` there. The reason I changes this was that the old logic relied on rank 0 knowing all IDs/strata, which is not always true and was causing problems with deep halos.

**Pull request merged**
