### PR TITLE
Don't assume the interpreter is called python3

### PR DESCRIPTION
**Pull request by dham**

### CODE REVIEW

**Comment by wence-** [comment]
I merged the (hopeful) test fix. Please rebase on top of master.

I think @JDBetteridge was going to comment about some other issues?

**Comment by wence-** [comment]
How has this merge gone so badly wrong? Can you just start from trunk and cherry-pick the three relevant commits?

**Comment by JDBetteridge** [comment]
> How has this merge gone so badly wrong? Can you just start from trunk and cherry-pick the three relevant commits?

No idea, have tried to recreate sequence of steps that would lead to this state unsuccessfully, opened  #1922 with relevant commits

**Comment by wence-** [comment]
You're welcome to force push here so that we don't lose the review process.

**Pull request merged**
