### PR TITLE
Migrate some of the lightweight checks to actions

### PR DESCRIPTION
**Pull request by wence-**
Means that these run in parallel to the main build.

### CODE REVIEW

**Comment by dham** [comment]
Looks like the Zenodo canary action didn't run.

**Comment by wence-** [comment]
I set it to only run on pushes to master.

**Comment by wence-** [comment]
> I set it to only run on pushes to master.

I guess maybe it makes sense to run in PRs too, in case we break stuff on our end.

**Comment by wence-** [comment]
> I guess maybe it makes sense to run in PRs too, in case we break stuff on our end.

Did that.

**Comment by ReubenHill** [comment]
Nice - so something that fails linting to a PR or draft PR, the linting will fail and the build step will be skipped?

**Comment by wence-** [comment]
> Nice - so if I push something that fails linting to a PR or draft PR, the linting will fail and the build step will be skipped?

The linting will fail, but the build tests will continue. These are now separate (parallel) checks that must pass.

**Comment by ReubenHill** [comment]
> > Nice - so if I push something that fails linting to a PR or draft PR, the linting will fail and the build step will be skipped?
> 
> The linting will fail, but the build tests will continue. These are now separate (parallel) checks that must pass.

Is it possible to force jenkins to not run in that case? Though I'm in two minds if that is desirable behaviour

**Comment by wence-** [comment]
> Is it possible to force jenkins to not run in that case? Though I'm in two minds if that is desirable behaviour

One would have to poke jenkins via some API to say "stop this build". Probably possible, but the jenkins docs are Not. Good.

I would like to migrate everything to actions, at which point it might be easier.

But AFAIAA, everyone opens PRs because they want the test suite to run, because no-one runs it locally. So stopping it straight away for lint purposes doesn't really help that much.

**Review by danshapero — DISMISSED** [review]
Looks good to me! Whether a lint failure should trigger an immediate build failure or not is maybe a policy decision for another day. But having lint failures show up earlier in the pipeline will definitely help give more rapid feedback which is good.

**Comment by wence-** [comment]
I realise I should use the pull_request_target selector instead of pull_request. Will do that tomorrow

**Pull request merged**
