### PR TITLE
Codecov

### PR DESCRIPTION
**Pull request by wence-**
Posts (hopefully) code coverage stats.

### CODE REVIEW

**Comment by wence-** [comment]
Seems to work...

**Comment by miklos1** [comment]
This is just coverage of the firedrake component by the Firedrake test suite, right? Would it be easy to report how much of other packages are covered by the Firedrake test suite?

**Comment by miklos1** [comment]
Is it line based coverage? Can you switch it to branch based?

**Comment by wence-** [comment]
Easy (we just have to add them to the list of `--cov` commands).  However, the magic source tracking in the GUI won't work I think.

**Comment by wence-** [comment]
I think you can have branch coverage (http://coverage.readthedocs.io/en/coverage-4.0.3/branch.html#branch).  Just need to figure out how to enable it.

**Comment by wence-** [comment]
So the coverage stuff will easily measure the coverage of everything.  However, that doesn't hook up with the GUI.  So you have to look in the build log to see anything useful.  So I'm tempted to remove that part.  But keep the branch based coverage setting.

**Comment by miklos1** [comment]
Yeah, I'm not interested in looking at the build log.

**Comment by wence-** [comment]
OK, so for the online stuff I'll only do coverage of firedrake itself.  I can add a `make coverage` target that does the necessary for local testing.

**Comment by mairieli** [comment]
Hi @wence- ! I've noticed that you changed the configuration of a bot in this PR. I am researching how to develop better GitHub bots. Would you be willing to participate in my research, answering a few questions?

**Pull request merged**
