### PR TITLE
Firedrake Manual release

### PR DESCRIPTION
**Pull request by JDBetteridge**
A PR for any and all errata found in the [Firedrake manual](https://github.com/firedrakeproject/firedrake/files/10816280/Firedrake.pdf)

I will update and upload the PDF on major changes, but please try to build the PDF yourself by running:
```bash
make latexpdf
```
in the `docs` directory.

### CODE REVIEW

**Comment by JDBetteridge** [comment]
Thanks Nacime!

> Here are things I noticed after a first high-level review:
> 
>     * We are repeating the authors' names on pages 1 and 2, is that deliberate? Also, I think we should probably add the manual version to page 1 (and probably make that page visually more attractive). What about having a first page that includes the logo, the manual version, and the date (more specific than just the year) and then placing the authors' names on the second page? Also, why don't we put affiliations?
This is all deliberate, the style is the one from David's book and I'm reluctant to change it too much. We can add more info to the edition as we see fit, but I doubt we'd release an edition any more regularly than every 6-months. I'd be very much in favour of only releasing an official pdf manual annually.  It's unusual to include author affiliation on the first page and space is also at a premium. 

>     * The warning message about `DumbCheckpoint` (resp. `HDF5File`) deprecation after 01/01/2023 on page 270 (resp. 272) is out of date.

This should be raised as a separate issue, the documentation is correct, this is exactly the warning raised!

>     * p.287: sumifiϕi -> ∑ifiϕi and everything should be on the same line
> 
>     * p.287: phii(x) -> ϕi(x)
> 
>     * Strange bold formatting in the docs of `evaluate_tlm` p.183 and `annotate_solve` p.197
> 
>     * Listing p.212-213 is hardly understandable

I will address these remaining issues in turn and post a new version of the pdf.

**Comment by ReubenHill** [comment]
> This should be raised as a separate issue, the documentation is correct, this is exactly the warning raised!
> 
> >

I've made a PR to say it will be 'soon' https://github.com/firedrakeproject/firedrake/pull/2853 .

**Comment by dham** [comment]
Please remove `team.py` and ensure everyone's publication name is used.

**Comment by JDBetteridge** [comment]
@nbouziani I have addressed the formatting errors you spotted, all but `evaluate_tlm` p.183. This is coming from pyadjoint and changing this goes against Google docstring style used by pyadjoint.

I'm not sure if there's an easy fix. For now I'm happy (and honestly surprised) this is only one broken docstring.

Latest version [Firedrake.pdf](https://github.com/firedrakeproject/firedrake/files/11325081/Firedrake.pdf)

**Comment by dham** [comment]
> @nbouziani I have addressed the formatting errors you spotted, all but `evaluate_tlm` p.183. This is coming from pyadjoint and changing this goes against Google docstring style used by pyadjoint.
> 
> I'm not sure if there's an easy fix. For now I'm happy (and honestly surprised) this is only one broken docstring.
> 
> Latest version [Firedrake.pdf](https://github.com/firedrakeproject/firedrake/files/11325081/Firedrake.pdf)

I think if we switch from using the `numpydoc` sphinx extension to `napoleon` then we get Google convention in addition to numpydoc.

**Comment by JDBetteridge** [comment]
Fixed! `napoleon` is now enabled + we have a watermark:

[Firedrake.pdf](https://github.com/firedrakeproject/firedrake/files/11345143/Firedrake.pdf)

**Comment by dham** [comment]
You might want to change the citing page to tell people to actually cite this manual, now that you've produced it!

**Comment by JDBetteridge** [comment]
> Thomas Gibson's mugshot appears twice on the team page. Once as Thomas Gregory, once as himself

So he does, let me fix that!

> You might want to change the citing page to tell people to actually cite this manual, now that you've produced it!

PR #2892 will take care of that. I will wait until this is merged, generate a DOI and then add the DOI to PR #2892

**Comment by wence-** [comment]
> Please remove `team.py` and ensure everyone's publication name is used.

Does this want to include affiliations, or not bother?

**Comment by JDBetteridge** [comment]
> > Please remove `team.py` and ensure everyone's publication name is used.
> 
> Does this want to include affiliations, or not bother?

We haven't bothered. Everyone who has provided a link gets a clickable link to their chosen page in authors.rst, the team page on firedrakeproject.org _and_ in the manual. Unless you feel especially strongly I was going to leave affiliations off the author page of the manual.

[Firedrake.pdf](https://github.com/firedrakeproject/firedrake/files/11346173/Firedrake.pdf) <-- uniquified Thomas'

**Comment by ReubenHill** [comment]
Will this, the list of authors, and any manual changes update whenever the website is rebuilt?

**Comment by ReubenHill** [comment]
> Will this, the list of authors, and any manual changes update whenever the website is rebuilt?

I ask because I plan to update the manual at some time soon with a more in depth overview of how to use `VertexOnlyMesh`

**Comment by JDBetteridge** [comment]
I feel so prepared for your question @ReubenHill : Checkout https://github.com/firedrakeproject/firedrake/pull/2871 where I am rebuilding the Firedrake website and manual and uploading to gh-pages (which we hope to migrate to soon) and https://github.com/firedrakeproject/firedrake/pull/2892 which adds the citation and a link to (a draft version with latest changes of) the manual to the website.

**Comment by JDBetteridge** [comment]
I think this is ready to go :eyes: 

[Latest](https://github.com/firedrakeproject/firedrake/files/11374708/Firedrake.pdf)

**Review by dham — APPROVED** [review]

**Pull request merged**
