### PR TITLE
BC components

### PR DESCRIPTION
**Pull request by wence-**
I think this allows setting (along with OP2/PyOP2#450) boundary conditions on a component of a vector function space.  Some rudimentary tests are added.  

The solves are xfailed because they don't do what I expect, but I'm not sure if this actually right.  Perhaps  I'm just misunderstanding what's going on.  Consider the following:

```python
from firedrake import *

parameters["pyop2_options"]["lazy_evaluation"] = False
parameters["assembly_cache"]["enabled"] = False
parameters["pyop2_options"]["debug"] = True
parameters["coffee"]["O2"] = False

mesh = UnitSquareMesh(1, 1)
V = VectorFunctionSpace(mesh, "CG", 1)

g = Function(V)

f = Constant((1, 2))

bcval = Constant((3, 3))

idx = 0
bc = DirichletBC(V, bcval, 1)

u = TrialFunction(V)
v = TestFunction(V)

a = dot(u, v)*dx
L = dot(f, v)*dx

expect = Function(V)

expect.assign(f)

expect.assign(bcval, subset=bc.node_set)

print expect.dat.data

solve(a == L, g, bcs=bc)

print g.dat.data
```

I expect to see 4 of the dofs set to the boundary condition value (3) and the other four to be the value of the input function.  I.e. I expect

```
3 3
3 3
1 2
1 2
```

Instead I see:

```
[[ 3.          3.        ]
 [ 3.          3.        ]
 [-0.42857143  1.28571429]
 [ 0.71428571  1.85714286]]
```

Dolfin produces what I would similarly call nonsense.  Ideas?

### CODE REVIEW

**Comment by dorugeber** [comment]
That's probably correct.  A similar thing happens just in 1D:

```
IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from firedrake import *

In [2]: mesh = UnitIntervalMesh(10)

In [3]: V = FunctionSpace(mesh, "CG", 1)

In [4]: out = Function(V)

In [5]: f = Function(V).assign(1)

In [6]: u = TrialFunction(V)

In [7]: v = TestFunction(V)

In [8]: a = u*v*dx

In [9]: L = f*v*dx

In [10]: bc = DirichletBC(V, 0.0, 1)

In [11]: solve(a == L, out, bcs=bc)
(snip)

In [12]: out.dat.data
Out[12]: array([ 0.        ,  1.26794919,  0.92820323,  1.01923789,  0.99484522,
        1.00138122,  0.99962989,  1.0000992 ,  0.99997329,  1.00000763,
        0.99999618])
```

**Comment by wence-** [comment]
OK, so I'm no less confused.

**Comment by dorugeber** [comment]
About why this happens, or about something else?

**Comment by wence-** [comment]
The former.

**Comment by dorugeber** [comment]
You're still testing against other functions, which results in an overshoot....

http://imgur.com/apg6gcB

**Comment by wence-** [comment]
OK, thanks.  I'll remove that test and attempt to write some better ones.

**Pull request merged**
