### PR TITLE
DONOTMERGE Test updated PETSc and SLEPc

### PR DESCRIPTION
**Pull request by connorjward**
@ScottMacLachlan if this passes then we can update our PETSc (and SLEPc) forks.

### CODE REVIEW

**Comment by connorjward** [comment]
Unfortunately crossed fingers were not enough. We are getting a couple of errors in `tests/output/test_io_mesh.py`. Since this is exactly @ksagiyam's domain I think the best thing to do is leave it up to him to fix it when he gets back from holiday.

Koki I have tracked the error as far as I dared. Here is a MFE:

```py
from firedrake import *
from pyop2.mpi import COMM_WORLD


fname = "dump.h5"
name = "mymesh"

mesh = UnitIntervalMesh(4, name=name)

with CheckpointFile(fname, "w", comm=COMM_WORLD) as f:
    f.save_mesh(mesh)

with CheckpointFile(fname, "r", comm=COMM_WORLD) as f:
    f.load_mesh(name=name)
```

It fails in serial as well as parallel.

According to `pytest tests/output/test_io_mesh.py -k "base[interval]" -s --pdb` the error is occuring at line 749 in `mesh.py` (`plex.setFromOptions()`):

```
Projects/firedrake-sandbox/firedrake/src/firedrake/firedrake/mesh.py", line 749 in __init__
  File "/home/connor/Code/Projects/firedrake-sandbox/firedrake/src/firedrake/firedrake/checkpointing.py", line 894 in _load_mesh_topology
  File "/home/connor/Code/Projects/firedrake-sandbox/firedrake/src/firedrake/firedrake/checkpointing.py", line 856 in load_mesh
  File "/home/connor/Code/Projects/firedrake-sandbox/firedrake/src/firedrake/tests/output/test_io_mesh.py", line 120 in _test_io_mesh_extrusion
  File "/home/connor/Code/Projects/firedrake-sandbox/firedrake/src/firedrake/tests/output/test_io_mesh.py", line 135 in test_io_mesh_base
```

If I run `python mfe.py -start_in_debugger` and then run the code I get the following traceback:

```
#0  0x00007f3e1cdd6b2d in PetscSignalHandler_Private () from /home/connor/.local/opt/petsc-firedrake/arch-default/lib/libpetsc.so.3.017
#1  <signal handler called>
#2  0x00007f3e1ce46674 in VecDuplicate () from /home/connor/.local/opt/petsc-firedrake/arch-default/lib/libpetsc.so.3.017
#3  0x00007f3e1d25a798 in DMPlexPermute () from /home/connor/.local/opt/petsc-firedrake/arch-default/lib/libpetsc.so.3.017
#4  0x00007f3e1d216410 in DMSetFromOptions_Plex () from /home/connor/.local/opt/petsc-firedrake/arch-default/lib/libpetsc.so.3.017
#5  0x00007f3e1d300bd5 in DMSetFromOptions () from /home/connor/.local/opt/petsc-firedrake/arch-default/lib/libpetsc.so.3.017
#6  0x00007f3e1e0e8664 in __pyx_pf_8petsc4py_5PETSc_2DM_30setFromOptions (__pyx_v_self=0x7f3e0d5d2810, __pyx_v_self=0x7f3e0d5d2810) at src/petsc4py.PETSc.c:271415
#7  __pyx_pw_8petsc4py_5PETSc_2DM_31setFromOptions (__pyx_v_self=0x7f3e0d5d2810, __pyx_args=<optimized out>, __pyx_kwds=0x0) at src/petsc4py.PETSc.c:9248
```

I'll build myself a debug version of PETSc and try to figure out some more but this is where I'm at.

**Comment by connorjward** [comment]
@ScottMacLachlan this bug only appears to affect checkpointing. If you want to build Firedrake with updated PETSc and SLEPc in the interim before this gets fixed then you can try:
```
python3 firedrake-install --package-branch petsc connorjward/merge-upstream *any other arguments*
```

If you need SLEPc you can also add `--package-branch slepc connorjward/merge-upstream`.

**Comment by ksagiyam** [comment]
https://gitlab.com/petsc/petsc/-/merge_requests/5245 has now been merged upstream.
@connorjward Could you update your `petsc` and `slepc` branches? I can test them in https://github.com/firedrakeproject/firedrake/pull/2438.

**Comment by connorjward** [comment]
> https://gitlab.com/petsc/petsc/-/merge_requests/5245 has now been merged upstream. @connorjward Could you update your `petsc` and `slepc` branches? I can test them in #2438.

Sure. All done.

**Comment by ksagiyam** [comment]
Thanks. Testing now.

**Pull request closed without merging**
