### PR TITLE
Ksagiyam/composed map

### PR DESCRIPTION
**Pull request by ksagiyam**
Use `op2.ComposedMap` for `VertexOnlyMesh`.

### CODE REVIEW

**Comment by ksagiyam** [comment]
Thanks! I just rebased the PyOP2 branch and started testing just in case. I will merge both branches if tests pass.

**Comment by ReubenHill** [comment]
Poke me for approval as necessary.  I see doc build is failing which surely isn't your fault

**Comment by ksagiyam** [comment]
Thanks!

**Comment by ksagiyam** [comment]
`master` doc build fails in the exact same way https://github.com/firedrakeproject/firedrake/actions/runs/3219340903/jobs/5383937108, so I will go ahead and merge this PR using my superpower.

**Pull request merged**
