### PR TITLE
Indexed vfs

### PR DESCRIPTION
**Pull request by wence-**
Fix silly bugs in indexed VFS.  Needs OP2/PyOP2#512.

### CODE REVIEW

**Comment by florianwechsung** [comment]
I think there is still a problem with this: when mixing component wise boundary conditions with full boundary conditions (i.e. for the entire vector space). 

```
from firedrake import *
from firedrake.petsc import PETSc
import numpy as np
mesh = UnitSquareMesh(2, 2)
V = VectorFunctionSpace(mesh, "CG", 2)
Q = FunctionSpace(mesh, "CG", 1)
W = V * Q

bc0 = DirichletBC(W.sub(0), Constant((0,0)), [3, 4])
bc1 = DirichletBC(W.sub(0), Constant((1,0)), 1)
bcs_full = [bc0, bc1]

bc0 = DirichletBC(W.sub(0).sub(0), 0, [3, 4])
bc1 = DirichletBC(W.sub(0).sub(1), 0, [3, 4])
bc2 = DirichletBC(W.sub(0).sub(0), 1, 1)
bc3 = DirichletBC(W.sub(0).sub(1), 0, 1)
bcs_cmp = [bc0, bc1, bc2, bc3]

bc0 = DirichletBC(W.sub(0), Constant((0,0)), [3, 4])
bc1 = DirichletBC(W.sub(0).sub(0), 1, 1)
bc2 = DirichletBC(W.sub(0).sub(1), 0, 1)
bcs_mixed = [bc0, bc1, bc2]

(u, p) = TrialFunctions(W)
(v, q) = TestFunctions(W)
a = inner(grad(u), grad(v))*dx + div(v)*p*dx + q*div(u)*dx

def ToNP(A):
    return A.M.handle.convert(PETSc.Mat.Type.DENSE).getDenseArray()
A_full = ToNP(assemble(a, bcs=bcs_full, mat_type = "aij"))
A_cmp = ToNP(assemble(a, bcs=bcs_cmp, mat_type = "aij"))
A_mixed = ToNP(assemble(a, bcs=bcs_mixed, mat_type = "aij"))
print np.allclose(A_full, A_cmp)
print np.allclose(A_mixed, A_full)
```

I'll check if it only occurs when using mixed function spaces or always.

**Comment by wence-** [comment]
You can access by just calling `__getitem__` on the matrix:  `A.M.handle[:, :]`

**Comment by wence-** [comment]
I think I know what's going on, the logic for deciding whether to throw things away in the generated code is slightly wrong.

We do:

`drop_full_row = 0 if rmap.vector_index is not None else 1`

In your case, we have a `rmap.vector_index` that is not None, so `drop_full_row` is False.  But, the map entry for a block, because we've also set some "drop both components" is something like:

```[-1610612737, -1610612738,          -3]```

So we correctly determine to drop both components for the first two entries, but then for the last entry, we have:

```c
                        if ( block_row < 0 ) {
                            tmp = -(block_row + 1);
                            discard = 1;
                            block_row = tmp & ~0x70000000;
                        }
                        for ( int k = 0; k < 2; k++ ) {
                            if ( discard && (0 || ((tmp & (1 << (30 - k))) != 0)) ) {
                                rowmap[j*2 + k] = -1;
                            } else {
                                rowmap[j*2 + k] = (block_row)*2 + k;
                            }
                        }
```

Let's walk through this:

```
block_row = -3
tmp = ~-3 = 2
discard = 1
block_row = (~-3) & ~0x70000000 = 2
```

So `discard` is True, so we'll hit the first branch, but `tmp` has no high bits set, so the second half of the condition will always evaluate to false.

So I think we need to make that condition evaluate:

```c
if (discard && (0 || !(tmp & 0x70000000) || ...)) {
...
}
```
So if we're discarding, and there are no high bits set, then discard the whole row/column.

Do you want to have a go (this is in pyop2/sequential.py around line 350.

**Comment by florianwechsung** [comment]
Brilliant, that fixed it. I have opened a pull request on PyOP2, should I add a test to firedrake checking this functionality once the pr has been merged?

**Comment by wence-** [comment]
I've merged the PyOP2 change and added your test.  Hopefully this will go green.

**Comment by florianwechsung** [comment]
brilliant, looks good!

**Pull request merged**
