### PR TITLE
Add --install femlium to Jenkinsfile install line

### PR DESCRIPTION
**Pull request by ReubenHill**
Should fix failing tests/regression/test_import_applications.py::test_import_app[femlium]

### CODE REVIEW

**Comment by ReubenHill** [comment]
This passes tests but not running the doc build - is this a known issue? @sv2518 I think I saw you had written something about it?

**Comment by wence-** [comment]
I restarted the docs build after I clicked through and noticed that github actions reported "we had an internal error".

**Comment by wence-** [comment]
See also https://www.githubstatus.com (most of the time you didn't do anything wrong!)

**Comment by sv2518** [comment]
So I think this is what is happening:

The doc build is running on a firedrake docker container. The latest updated docker container would have been pushed by the previous merge into master. Since master was failing the new docker (with the new loopy) has never been pushed.

There is already an issue open here https://github.com/firedrakeproject/firedrake/issues/2070 to fix the action, we basically should add a firedrake-update to that action. I tried that but the update did not do the right thing, because there are two firedrakes in the action. In this PR https://github.com/firedrakeproject/firedrake/pull/2071 I change the action so that there is only the firedrake on the container, but for some reason the firedrake-update was breaking in the container. I still need to investigate why.

**Comment by sv2518** [comment]
I am just a bit confused why the build actions is not even failing properly anymore. Previously the build action fail would tell  you that it cannot find one of the loopy functions we import.

**Comment by wence-** [comment]
> I am just a bit confused why the build actions is not even failing properly anymore. Previously the build action fail would tell you that it cannot find one of the loopy functions we import.

Did we get a successful loopy-based build through?

**Comment by sv2518** [comment]
> Did we get a successful loopy-based build through?

Firedrake-build (=firedrake install on Jenkins on master) yes, but we don't have the docker of it yet, because we need this PR so that we pass all tests. The docker page for firedrake says "Updated 5 days ago".

**Review by sv2518 — APPROVED** [review]

**Comment by wence-** [comment]
Thanks

**Pull request merged**
