### PR TITLE
ufl#208 has removed ufl.algorithms.multifunction. Use ufl.corealg.multifunction instead.

### PR DESCRIPTION
**Pull request by francesco-ballarin**

### CODE REVIEW

**Comment by francesco-ballarin** [comment]
FYI, I guess that firedrake ufl fork doesn't include upstream#208 yet, but this should not be a blocker for approving the workflow runs. ufl.algorithms.multifunction had always actually been importing ufl.corealg.multifunction, so this change should be backward compatible.

**Comment by nbouziani** [comment]
Yes, given that UFL upstream was merged earlier today, this is needed to not break CI. I have noticed that problem in another PR (#2294). I think this is ready to go.

**Review by nbouziani — APPROVED** [review]

**Comment by francesco-ballarin** [comment]
CI failure looks unrelated. Is the `torch` coupling getting fixed in another PR?

**Comment by nbouziani** [comment]
> CI failure looks unrelated. Is the `torch` coupling getting fixed in another PR?

Yes, those failures are expected and are fixed in another PR.

**Pull request merged**
