### PR TITLE
mg: Fix grid transfer on extruded mesh hierarchies that refine in the extruded direction

### PR DESCRIPTION
**Pull request by wence-**
I augmented @MelodyShih's test, but now the discontinuous injections fail.

### CODE REVIEW

**Comment by wence-** [comment]
>  but now the discontinuous injections fail.

I did a bork. I think things now work.

**Comment by wence-** [comment]
Let's wait to see if jenkins is happy and then I will undraft this. @MelodyShih can you check this branch works for your stuff?

**Comment by MelodyShih** [comment]
@wence- This fixes it! Thank you for looking into the issue.

**Comment by wence-** [comment]
The test I added failed in complex mode, now fixed I hope.

**Comment by wence-** [comment]
Ready for review.

**Review by MelodyShih — APPROVED** [review]
Looks good to me.

**Pull request merged**
