### PR TITLE
Add install support and demo of GenEO preconditioner using geneo4PETSc

### PR DESCRIPTION
**Pull request by wence-**

### CODE REVIEW

**Comment by wence-** [comment]
This is work with @FredericN at LJLL.

**Comment by wence-** [comment]
Needs MatIS support from OP2/PyOP2#551.

**Comment by wence-** [comment]
I hope this will now build on Jenkins. I think it is ready to go for now. When we get better support for subdomains we should revisit how we build MatIS objects: we should just make the pieces by hand.

**Comment by wence-** [comment]
This is presently not building on Jenkins due to lack of dependencies, particularly boost-mpi. I think I can modify the upstream package to avoid the need for boost-mpi, so I will endeavour to do that.

**Comment by FredericN** [comment]
Hi Lawrence,

 actually, if you can remove the dependency on boost, it will be good. 

  best regards,

    Frédéric

**Comment by FredericN** [comment]
Hi Lawrence,

 actually, if you can remove the dependency on boost, it will be good. 

  best regards,

    Frédéric

> Le 5 févr. 2019 à 13:59, Lawrence Mitchell <notifications@github.com> a écrit :
> 
> This is presently not building on Jenkins due to lack of dependencies, particularly boost-mpi. I think I can modify the upstream package to avoid the need for boost-mpi, so I will endeavour to do that.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

—————————————————————————————————————
Frederic Nataf
Senior Scientist CNRS
Laboratoire Jacques Louis Lions, CNRS UMR 7598, Sorbonne Université, Campus Pierre et Marie Curie
Equipe Alpines à INRIA
HPDDM Open source project: https://github.com/hpddm
An Introduction to Domain Decomposition Methods: Algorithms, Theory and Parallel Implementation: http://bookstore.siam.org/ot144/
Coordonnées: 4 place Jussieu
75252 Paris Cedex 05, France
http://www.upmc.fr/fr/universite/campus_et_sites/a_paris_et_en_idf/jussieu.html , bureau 319 Tour 15/25
mel: nataf@ann.jussieu.fr  http://www.ann.jussieu.fr/~nataf/
Tel: 33 (0)1 44 27 93 03     PORTABLE:    07 60 01 07 96
Fax:33 (0)1 44 27 72 00
---------------------------------------------------------------------------

**Comment by FredericN** [comment]
Dear David,

  very good news. How can I try it? Is there some example file?

  best regards,

      Frédéric 

> Le 2 août 2019 à 16:55, David A. Ham <notifications@github.com> a écrit :
> 
> Closed #1354.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

—————————————————————————————————————
Frederic Nataf
Senior Scientist CNRS
Laboratoire Jacques Louis Lions, CNRS UMR 7598, Sorbonne Université, Campus Pierre et Marie Curie
Equipe Alpines à INRIA
HPDDM Open source project: https://github.com/hpddm
An Introduction to Domain Decomposition Methods: Algorithms, Theory and Parallel Implementation: http://bookstore.siam.org/ot144/
Coordonnées: 4 place Jussieu
75252 Paris Cedex 05, France
http://www.upmc.fr/fr/universite/campus_et_sites/a_paris_et_en_idf/jussieu.html , bureau 319 Tour 15/25
mel: nataf@ann.jussieu.fr  http://www.ann.jussieu.fr/~nataf/
Tel: 33 (0)1 44 27 93 03     PORTABLE:    07 60 01 07 96
Fax:33 (0)1 44 27 72 00
---------------------------------------------------------------------------

**Comment by dham** [comment]
This was closed because @wence- doesn't think it is straightforward to get it into a mergeable state, and that the preconditioner concerned will become more straightforwardly implementable directly in Firedrake as the sub mesh capabilities that @ksagiyam is working on progress.

**Comment by wence-** [comment]
@FredericN apologies that I never got this all the way there. I do want to pick this up again once (as David says) @ksagiyam's work on submeshes arrives. That should enable an implementation of geneo that is closer to the way it is done in freefem (namely by writing a preconditioner at the level of UFL, rather than by manipulating matrices).

**Comment by prj-** [comment]
FWIW, I've been working on interfacing [HPDDM](https://github.com/hpddm/hpddm) (an efficient implementation of multilevel GenEO) in PETSc, cf. this [PR](https://bitbucket.org/petsc/petsc/pull-requests/1945/wip-add-download-hpddm). This is already in a working state (don't be afraid of the [WIP] flag), but Stefano wants to get fancier things working before the merge (for nonlinear preconditioning). This is rather straightforward to interface, one just needs a local matrix and a local index set, as displayed in [ex76.c](https://bitbucket.org/petsc/petsc/pull-requests/1945/wip-add-download-hpddm/diff#chg-src/ksp/ksp/examples/tutorials/ex76.c).

**Comment by wence-** [comment]
@prj-, OK, great. I think again, this will be simplified if I can build the local neumann matrices "by hand" -> submesh support in Firedrake will enable this. Then I build the MatIS, but just set all the relevant data in it correctly (rather than doing a rather fragile dance that I was trying previously).

**Comment by prj-** [comment]
@wence- I completely agree with what you are saying. The takeaway message from my previous post was rather: if you don't want to bother reimplementing all the GenEO linear algebra (once your are done with the submesh support), it is quite easy to just use PCHPDDM. If you do the algebra yourself, I'd be happy to compare this with our implementation (geneo4PETSc was rather not optimized for performance...).

**Pull request closed without merging**
