### PR TITLE
Allow user to pass bindings for coefficients in assembly

### PR DESCRIPTION
**Pull request by wence-**
Allows separation of symbolic UFL form from the data it will be
assembled with. Useful for avoiding use of ufl.replace in adjoint
annotation and replay.

@jrmaddison requested this, or something similar, so that in tlm_adjoint, the storage (which might want to be thrown away) can be separated from the symbolic form. With this interface, we can do a one-time `ufl.replace` on the form when taping, and then have a fast assembly with coefficients by providing a map `{symbolic_coefficient: real_coefficient}`. James reports this makes a large (positive) improvement to the speed: previously he was doing this himself by having fake coefficients which were mutated to add data at the correct moment.

### CODE REVIEW

**Comment by jrmaddison** [comment]
This is a source of irritation for small problems, where the cost of ufl.replace can be significant (see https://github.com/FEniCS/ufl/pull/14).

This is a particular issue in an adjoint calculation for the case where a forward equation is used multiple times, and in the worst case you must call ufl.replace once per adjoint term (or else differentiate the residual once per term), repeatedly, each time the adjoint equation is solved.

**Comment by ksagiyam** [comment]
I think it looks good.

**Comment by jrmaddison** [comment]
The following construct:

```
from firedrake import *

import ufl

mesh = UnitIntervalMesh(10)
space = FunctionSpace(mesh, "Lagrange", 1)
test, trial = TestFunction(space), TrialFunction(space)

m_c = ufl.classes.Coefficient(space)

m_v = Function(space, name="m_v")
m_v.assign(1.0)

A = assemble(inner(test, m_c * trial) * dx, bindings={m_c: m_v})

b = assemble(inner(test, Constant(1.0)) * dx)

F = Function(space, name="F")
solver = LinearSolver(A)
solver.solve(F, b)
```

leads to an error

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    A = assemble(inner(test, m_c * trial) * dx, bindings={m_c: m_v})
  File "[...]/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 100, in assemble
    loops = tuple(loops)
  File "[...]/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 239, in _assemble
    for coeff in f.coefficients()):
  File "[...]/firedrake/src/firedrake/firedrake/assemble.py", line 239, in <genexpr>
    for coeff in f.coefficients()):
AttributeError: 'Coefficient' object has no attribute 'function_space'
```

The original Form, stored on the Matrix.a attribute, refers to the incorrect Coefficient.

**Comment by wence-** [comment]
@jrmaddison sorry, I realise I've dropped the ball here.

How about if we wrap this up in a context manager, so you say:

```python
with form_bindings(form, bindings):
   ...
```

And this arranges that all the assemble calls that happen inside this block get the right coefficients.

**Comment by jrmaddison** [comment]
I think that still doesn't resolve the issue of the deferred boundary condition lifting.

This specific issue could be resolved by lifting at the time of the bilinear form assembly and caching the RHS term, but that wouldn't fix other cases where Matrix.a is used after assembly.

Note that the current approach can lead to inconsistencies, e.g.

```
from firedrake import *
import numpy as np

mesh = UnitIntervalMesh(10)
space = FunctionSpace(mesh, "Lagrange", 1)
test, trial = TestFunction(space), TrialFunction(space)

F = Function(space, name="F")
F.assign(2.0)

bc = DirichletBC(space, 2.0, "on_boundary")

A = assemble(inner(test, F * trial) * dx, bcs=bc)
b = assemble(inner(test, Constant(1.0)) * dx)
solver = LinearSolver(A, solver_parameters={"ksp_type": "preonly",
                                            "pc_type": "cholesky"})

F.assign(1.0)  # Introduce an inconsistency between A and A.a

u = Function(space, name="u")
solver.solve(u, b)  # Boundary condition applied incorrectly

u_ref = Function(space, name="u_ref")
solve(inner(test, F * trial) * dx == inner(test, Constant(1.0)) * dx,
      u_ref, bc, solver_parameters={"ksp_type": "preonly",
                                    "pc_type": "cholesky"})

# Non-zero error
print(f"error norm = "
      f"{np.sqrt(assemble(inner(u - u_ref, u - u_ref) * dx)):.16e}")
```

**Comment by wence-** [comment]
Given that dolfin are also throwing out backward compat (and this has never been an API compatibility we had anyway), perhaps we should think about how to redesign the linear solver interface so this all works "as expected".

**Pull request closed without merging**
