### PR TITLE
adding a new demo that solves the one-layer quasigeostrophic model.

### PR DESCRIPTION
**Pull request by francispoulin**

### CODE REVIEW

**Comment by dham** [comment]
Hi Francis,

This demo appears to contain no actual code. Are you sure you meant to create this pull request already?

**Comment by francispoulin** [comment]
Hello,

Sorry for my mixup.

I agree that when I look on github on my qg_demo branch

https://github.com/francispoulin/firedrake/tree/qg_demo/demos/quasigeostrophy_1layer

I only see the rst. But I did git push to upload everything.  Also, when I do git status it says that my branch is up to date.

I really don't understand why one file would be there and not the other.  Any ideas?

Francis


------------------
Francis Poulin
Associate Professor
Department of Applied Mathematics
University of Waterloo

email:           fpoulin@uwaterloo.ca
Web:            https://uwaterloo.ca/poulin-research-group/
Telephone:  +1 519 888 4567 x32637

________________________________

**Comment by miklos1** [comment]
Hmm... have you forgotten to `git add`?

**Comment by francispoulin** [comment]
Hello,

I did a git add all and my computer says that my branch qg_demo is up to date.  Yes, there is clearly a file missing from the github repo.


am-laptop24:quasigeostrophy_1layer fpoulin$ git status

On branch qg_demo

Your branch is up-to-date with 'origin/qg_demo'.

nothing to commit, working directory clean

Francis

------------------
Francis Poulin
Associate Professor
Department of Applied Mathematics
University of Waterloo

email:           fpoulin@uwaterloo.ca
Web:            https://uwaterloo.ca/poulin-research-group/
Telephone:  +1 519 888 4567 x32637

________________________________

**Comment by wence-** [comment]
Hi Francis,

because we write demos in rst (and the rst contains the code that runs the demo as well as the documentation) we gitignore `.py` files in the demos directory (which is why `git status` says there's no problem).  So I presume you have separately written the rst documenting the code and a `.py`.  You probably want to paste the contents of the `.py` as a `.. code-block:: ` into the rst.

**Comment by francispoulin** [comment]
I have updated the rst file to include the code.  I do think it would be nice to have the python script there as well, if at all possible.

**Comment by francispoulin** [comment]
Hello Lawrence,

Thanks for pointing that out. I have now updated the rst to include the code.  I do think it would be nice to have python scripts there if possible since it's easier for people to download.  Maybe there's a different way of doing that?

I am pretty sure there will need to be some changes before the demo is suitable.  Please let me know what you would like and I will try and fix it up when I can.

Francis



------------------
Francis Poulin
Associate Professor
Department of Applied Mathematics
University of Waterloo

email:           fpoulin@uwaterloo.ca
Web:            https://uwaterloo.ca/poulin-research-group/
Telephone:  +1 519 888 4567 x32637

________________________________

**Comment by wence-** [comment]
Aha, so what happens when we generate the website is that the rst is converted into a runnable Python file. All the commentary and maths become comments and the code blocks become runnable Python. These are then linked from the generated demo page for download. For example at the bottom of http://firedrakeproject.org/demos/burgers.py.html is a link to the python version http://firedrakeproject.org/demos/burgers.py when one can download and run. These demos are even run as part of the test suite.

**Comment by francispoulin** [comment]
That is a very nice way of doing things.  Thanks for explaining it to me.

I hope that my demo is set up correctly for this to happen. If not I'll try and fix it up.

Francis

**Comment by wence-** [comment]
Dear Francis,

apologies this sat around for so long.  I have now had a little time to go through it and added a bit more exposition to the code part of the demo.  It is now merged.  You can see the resulting html version here http://firedrakeproject.org/demos/qg_1layer_wave.py.html.

Thanks!

**Comment by francispoulin** [comment]
Dear Lawrence,

Thanks for fixing this up and posting it.  Thanks to Jemma we now have a 3D version of the QG model.  The differences are very small so I don't think it would be worth a whole new demo but it is around if you ever want to include it anywhere.

Cheers, Francis



------------------
Francis Poulin
Associate Professor
Department of Applied Mathematics
University of Waterloo

email:           fpoulin@uwaterloo.ca
Web:            https://uwaterloo.ca/poulin-research-group/
Telephone:  +1 519 888 4567 x32637

________________________________

**Pull request merged**
