### PR TITLE
Tsfc firedrake update

### PR DESCRIPTION
**Pull request by wence-**
cd to the top directory of the firedrake virtualenv.
. ./bin/activate
cd src/firedrake/
git pull
./scripts/firedrake-install --rebuild-script
firedrake-update --clean

### CODE REVIEW

**Comment by wence-** [comment]
I'm confused about the rebuild script step.  Do I have to update the firedrake source tree by hand first?

**Comment by dham** [comment]
Fixed

**Comment by miklos1** [comment]
`git update` doesn't exit. `git pull`?

**Comment by miklos1** [comment]
Note: Your Firedrake install options must be specified at

    ./scripts/firedrake-install --rebuild-script

**Comment by wence-** [comment]
If the virtualenv doesn't contain `virtualenv` then `firedrake-update --clean` installs and prompts to run `firedrake-install` again.  As in #690

**Comment by dham** [comment]
OK, well we can't actually fix that fully on this run - but we can fix the error message.

**Comment by miklos1** [comment]
We might also want to remind users to clean cache after update: `firedrake-clean`

**Comment by miklos1** [comment]
Are there any outstanding issues, or can this (and the other branches) land?

**Comment by dham** [comment]
I think this can land. The builders are past the install phase.

**Comment by miklos1** [comment]
@dham: OK, I'm doing it.

**Comment by miklos1** [comment]
Already in master.

**Pull request closed without merging**
