### PR TITLE
added flooddrake parameters

### PR DESCRIPTION
**Pull request by alsgregory**

### CODE REVIEW

**Comment by miklos1** [comment]
Do we really want this here? Couldn't this just go to flooddrake?

**Comment by wence-** [comment]
We definitely don't want this.

@alsgregory, you can use the firedrake parameters dictionary in flooddrake directly without needing to touch firedrake code at all.  Please do that.

**Comment by alsgregory** [comment]
Ok ok. I only put this here because @dham suggested this. I will delete.

**Comment by dham** [comment]
Just for the record. I did not suggest this. I suggested what wence also suggested.

**Pull request closed without merging**
