### PR TITLE
Voting algorithm for VertexOnlyMesh

### LINKED ISSUE #2178: `TypeError` and Points missing in VertexOnlyMesh
When I use the `VertexOnlyMesh`, there are some errors and sometimes points are missing. See the below example.
```
from firedrake import *

# logging.set_level(logging.DEBUG)
def test_vom(n1=8, n2=16, quadrilateral=False):

    m = UnitSquareMesh(n1, n1, quadrilateral=quadrilateral)
    m_ref = UnitSquareMesh(n2, n2, quadrilateral=quadrilateral)
    coords_ref = m_ref.coordinates.dat.data
    vm = VertexOnlyMesh(m, coords_ref)
    W = FunctionSpace(vm, "DG", 0)

    print('\tThere are %d points'%len(coords_ref))
    print('\tThere are %d dofs in space W'%W.dof_count)

print('Test with quadrilateral=False')
test_vom(n1=8, n2=16, quadrilateral=False)

print('Test with quadrilateral=True')
test_vom(n1=8, n2=16, quadrilateral=True)

print('Test with larger n1 and quadrilateral=False')
test_vom(n1=10, n2=16, quadrilateral=False)
```

The errors are list below:
```
(firedrake) firedrake@c0a3031a6d9f:~$ python test.py
firedrake:WARNING OMP_NUM_THREADS is not set or is set to a value greater than 1, we suggest setting OMP_NUM_THREADS=1 to improve performance
Test with quadrilateral=False
/home/firedrake/firedrake/src/firedrake/firedrake/parloops.py:130: LoopyWarning: 'lang_version' was not passed to make_function(). To avoid this warning, pass lang_version=(2018, 2) in this invocation. (Or say 'from loopy.version import LOOPY_USE_LANGUAGE_VERSION_2018_2' in the global scope of the calling frame.)
  knl = loopy.make_function(kernel_domains, instructions, kargs, seq_dependencies=True,
        There are 289 points
        There are 289 dofs in space W
Test with quadrilateral=True
/home/firedrake/firedrake/src/firedrake/firedrake/parloops.py:130: LoopyWarning: 'lang_version' was not passed to make_function(). To avoid this warning, pass lang_version=(2018, 2) in this invocation. (Or say 'from loopy.version import LOOPY_USE_LANGUAGE_VERSION_2018_2' in the global scope of the calling frame.)
  knl = loopy.make_function(kernel_domains, instructions, kargs, seq_dependencies=True,
        There are 289 points
        There are 256 dofs in space W
Test with larger n1 and quadrilateral=False
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    test_vom(n1=10, n2=16, quadrilateral=False)
  File "test.py", line 10, in test_vom
    vm = VertexOnlyMesh(m, coords_ref)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/firedrake/src/firedrake/firedrake/mesh.py", line 2002, in VertexOnlyMesh
    dmcommon.label_pic_parent_cell_info(swarm, mesh)
  File "firedrake/cython/dmcommon.pyx", line 2710, in firedrake.cython.dmcommon.label_pic_parent_cell_info
TypeError: an integer is required
```

After changing the default tolerance value of `locate_cell_and_reference_coordinate` to `1e-6` by
```
import firedrake
firedrake.mesh.MeshGeometry.locate_cell_and_reference_coordinate.__defaults__ = (1e-6,)
```
the error gone, but some points still missing
```
Test with quadrilateral=False
	There are 289 points
	There are 289 dofs in space W
Test with quadrilateral=True
	There are 289 points
	There are 256 dofs in space W
Test with larger n1 and quadrilateral=False
	There are 289 points
	There are 289 dofs in space W
```

By the way, another question here is the `VertexOnlyMesh` seems only find the points locally when using it in parallel. It seems related to the parameters of `DMSwarmSetPointCoordinates` in PETSc.

### PR DESCRIPTION
**Pull request by ReubenHill**
Fixes the VertexOnlyMesh part of #2790. To fix `.at` we need to make a VertexOnlyMesh when doing the point location.

Note this fixes #2178 - points will now redistribute to their appropriate location when `redundant=False`

This also changes the default VertexOnlyMesh creation behaviour to throw a `ValueError` when points are lost.

### CODE REVIEW

**Review by dham — CHANGES_REQUESTED** [review]
I think this is very good. I just found two possible small errors in docstrings.

**Comment by ReubenHill** [comment]
> I think this is very good. I just found two possible small errors in docstrings.

Thanks! I'll fix the docstring mistakes then tidy up the commit history. I'll ping you when that's done.

**Comment by wence-** [comment]
One of the commits says:

> This introduces a global index numbering and rank labelling for DMSwarm
points. Note that we can't use the in-build DMSwarm numbering in the
field named 'DMSwarmField_pid' because there's a bug in petsc4py which
makes it inaccessible (it uses PETSC_INT64 which is not in petsc4py).

Is this a bug we can fix in petsc4py? If we did, would that simplify this PR?

**Comment by wence-** [comment]
> One of the commits says:
> 
> > This introduces a global index numbering and rank labelling for DMSwarm
> > points. Note that we can't use the in-build DMSwarm numbering in the
> > field named 'DMSwarmField_pid' because there's a bug in petsc4py which
> > makes it inaccessible (it uses PETSC_INT64 which is not in petsc4py).
> 
> Is this a bug we can fix in petsc4py? If we did, would that simplify this PR?

It might be sufficient to do:

```diff
diff --git a/src/binding/petsc4py/src/PETSc/DMSwarm.pyx b/src/binding/petsc4py/src/PETSc/DMSwarm.pyx
index 64433d97ed9..60d254022fd 100644
--- a/src/binding/petsc4py/src/PETSc/DMSwarm.pyx
+++ b/src/binding/petsc4py/src/PETSc/DMSwarm.pyx
@@ -101,6 +101,7 @@ cdef class DMSwarm(DM):
         if ctype == PETSC_REAL:    typenum = NPY_PETSC_REAL
         if ctype == PETSC_SCALAR:  typenum = NPY_PETSC_SCALAR
         if ctype == PETSC_COMPLEX: typenum = NPY_PETSC_COMPLEX
+        if ctype == PETSC_INT64:   typenum = NPY_INT64
         assert typenum != -1
         cdef npy_intp s = <npy_intp> nlocal * blocksize
         return <object> PyArray_SimpleNewFromData(1, &s, typenum, data)
diff --git a/src/binding/petsc4py/src/PETSc/petscsys.pxi b/src/binding/petsc4py/src/PETSc/petscsys.pxi
index f0af69f42e7..8f735705674 100644
--- a/src/binding/petsc4py/src/PETSc/petscsys.pxi
+++ b/src/binding/petsc4py/src/PETSc/petscsys.pxi
@@ -2,6 +2,7 @@ cdef extern from * nogil:
 
     ctypedef enum PetscDataType:
         PETSC_INT
+        PETSC_INT64
         PETSC_REAL
         PETSC_SCALAR
         PETSC_COMPLEX
```

**Comment by ReubenHill** [comment]
> 

It wouldn't simplify the PR, it would just keep the DMSWARM fields consistent with those a DMSWARM user would expect. We'd still need to rely on our voting algorithm whilst we don't have agreement between PETSc and Firedrake on cell numbering (e.g. for mesh's made from coordinate fields). At that point all of this functionality could be moved down into PETSc.

**Pull request merged**
