### PR TITLE
Refactor quadrilaterals across Firedrake/UFL/FFC/FIAT 

### PR DESCRIPTION
**Pull request by miklos1**
This removes the ugly `_ufl_finite_element` and `_ufl_vector_element` wrappers from Firedrake. FFC pull request 67 replaces their functionality and adds a convenient syntax for creating H(div) and H(curl) conforming finite elements, mostly solving Firedrake issue #447. These changes also update the test cases to use the new, easier syntax.

### CODE REVIEW

**Comment by dorugeber** [comment]
Yes, do it.

For people not in {me, Miklos, wence}, a high-level summary is that this causes UFL quadrilateral elements to be generated in the form.  In the past, we had forced the user to build their own element (in the RT case), or we generated an OuterProductElement (in the CG/DG case).

The FFC change causes the UFL quadrilateral element to be mapped to "the right" (sum of) (product of) FIAT elements.

**Comment by dorugeber** [comment]
Note that there is one overhanging issue that we haven't decided on yet: should FIAT maintain its own representation of quadrilateral elements?

I understand that it would make Miklos's job somewhat easier (particularly when extruding quad meshes) if the entity dofs were 'flattened' into
```
{0: ...
1: ...
2: ...}
```
rather than
```
{(0, 0): ...
(0, 1): ...
(1, 0): ...
(1, 1): ...}
```

**Comment by miklos1** [comment]
After some more investigation on the extrusion front, I find that implementing extruded quadrilaterals would require extraordinary amount of ugly hacking in Firedrake, if I did not push the "element flattening" down to the core, which is `two_product_cell` and `TensorFiniteElement`.

**Comment by dorugeber** [comment]
In that case, I'd suggest making FIAT quad elements.  I assume that these should construct an appropriate enriched element or TFE, and call the appropriate methods except where you want flattening to occur.

We current have several FIAT elements doing this already, including Enriched, Discontinuized, Trace, Facetize and Interiorize.

Another possibility is to implement a more general Flattenize FIAT element which takes in an element on interval x interval and returns an element on a 'flattened' quad.

**Comment by miklos1** [comment]
Things changed.

These changes now move many quadrilateral support related hacks from Firedrake to FFC/FIAT and UFL (simplifies future extrusion support on quadrilaterals), plus add an easy syntax for defining RTCF and RTCE function spaces on both quadrilateral and extruded interval meshes.

FIAT and UFL changes should be merged first, then Firedrake and FFC changes should be merged at the same time, otherwise things break.

**Comment by wence-** [comment]
Tick.

**Pull request merged**
