### PR TITLE
firedrake-install: Use - in arguments rather than _

### PR DESCRIPTION
**Pull request by kynan**
argparse implicitly converts flags with dashes to variables with underscores.

### CODE REVIEW

**Comment by miklos1** [comment]
+1

**Comment by dham** [comment]
Is this really worth it? It breaks the existing interface and so will be noticed by current users (the test fails are, in fact, indicative of this).

**Comment by kynan** [comment]
Test and docs now fixed.

Yes, it will be noticed by users, but they can just do `-h` to see the changed flags, no?

The idea is to follow the GNU convention of separating multi-word long options with dashes.

**Comment by dham** [comment]
I think your faith in user ability is overstated. Note that the announcement of the libspatialindex change was not noticed by everyone. Can we just keep both spellings?

**Comment by kynan** [comment]
Yes we can and I have done so now! Also fixed the metavars for `--package-branch` while at it.

**Pull request merged**
