### PR TITLE
Remove superfluous words and numbers from extrusion test file names

### PR DESCRIPTION
**Pull request by miklos1**
Test file names such as `test_extrusion_2_identity.py` are annoying to type even with tab-autocompletion, especially since they are already in a separate directory called `extrusion`. The numbers also don't mean much. Plus these files are not consistently named at the moment.

### CODE REVIEW

**Comment by dorugeber** [comment]
Fine.

**Comment by miklos1** [comment]
Unfortunately, it is not great when running `make alltest`:
https://gist.github.com/miklos1/15afa5a1f37773e098ab

py.test wants each file that is run in one session to have a unique name. :(

**Comment by dorugeber** [comment]
booo

**Comment by miklos1** [comment]
I put back `_extrusion` where necessary, but at the end of name which is autocomplete friendly.
Let's see if I can get it approved now.

**Pull request merged**
