### PR TITLE
Annotate +=, *=, etc.

### PR DESCRIPTION
**Pull request by jwallwork23**
This PR ensures +=, *=, -= and /= are correctly annotated for `Function`s. The failure reported in #1860 is fixed by these changes. For example, the following test passes.

```
from firedrake import *
from firedrake_adjoint import *


# Create source and target functions in P1 space
mesh = UnitSquareMesh(1, 1)
P1 = FunctionSpace(mesh, "CG", 1)
source = Function(P1)
src = 1.0
source.assign(src)
control_src = Control(source)
target = Function(P1)
tgt = -2.0
target.assign(tgt)
control_tgt = Control(target)
target += source

# Try to compute gradient of some functional w.r.t. source
out = Function(P1)
out.assign(target)
J = assemble(out*dx)
assert np.isclose(J, src + tgt), J

tgt = -2.0
rf_src = ReducedFunctional(J, control_src)
for src in np.linspace(1, 3, 3):
    assert np.isclose(rf_src(src), src + tgt)

rf_tgt = ReducedFunctional(J, control_tgt)
src = 1.0
for tgt in np.linspace(-2, 1, 3):
    assert np.isclose(rf_tgt(tgt), src + tgt)
```

### CODE REVIEW

**Comment by ReubenHill** [comment]
FYI issue #1980 might be relevant here

**Comment by nbouziani** [comment]
Naive question: Are there circumstances where operations such as "a+=b" would not be equivalent to "a.assign(a+b)" (i.e. where using FunctionAssignBlock would not be appropriate) ?  

Apart from that, the PR looks all good for me. Would it be possible to add tests ?

**Comment by jwallwork23** [comment]
@nbouziani So I added a test and in it identified one case where assign might not DTRT. For a function in P1 space, `f *= g` does a point-wise multiply, which isn't the same as the expression `f*g` in general. I guess the same applies for `f /= g`, but you don't see that in the test because the two functions coincide.

**Comment by wence-** [comment]
> `f *= g` does a point-wise multiply, which isn't the same as the expression `f*g` in general

This is a "surprise" we should fix. Can you show an example?

**Comment by jwallwork23** [comment]
```
>>> from firedrake import *
>>> mesh = UnitSquareMesh(4, 4)
>>> V = FunctionSpace(mesh, "CG", 1)
>>> x, y = SpatialCoordinate(mesh)
>>> f = interpolate(x + 1, V)
>>> g = interpolate(x + 1, V)
>>> g *= f
>>> assemble(g*dx)
2.3437499999999973
>>> assemble(f*f*dx)
2.3333333333333304
```

**Comment by jwallwork23** [comment]
I guess this happens because g is in P1 space, but f*f is quadratic?

**Comment by jwallwork23** [comment]
Okay I now realise this is a problem with my test, not with the implementation (see latest commit). Sorry!

**Review by wence- — APPROVED** [review]
Thanks (note that the adjoint of `*=` and `/=` is wrong, because the adjoint doesn't do the right thing for nonlinear assignment)

**Pull request merged**
