### PR TITLE
firedrake-update shall update itself first

### PR DESCRIPTION
**Pull request by miklos1**
To solve the bootstrapping problem in updating Firedrake.

### CODE REVIEW

**Comment by wence-** [comment]
Looks sane.

**Comment by wence-** [comment]
This did not appear to work correctly.  I have fixed this, I hope, and added information to the docs that one should run `firedrake-update` in the activated virtualenv.  Finally, I now test `firedrake-update` on travis.

**Comment by dham** [comment]
looks reasonable, though I haven't run it.

**Comment by miklos1** [comment]
Rebased because of merge conflict.

**Comment by wence-** [comment]
And again.

**Comment by wence-** [comment]
OK, this is finally passing, and travis now tests both firedrake-install and firedrake-update, so will merge.

**Pull request merged**
