### PR TITLE
Add a recent journal article to user publications

### PR DESCRIPTION
**Pull request by alexanderzimmerman**
This also removes the corresponding preprint published for the first time on arXiv back in 2019.

To do:
- [x] Verify that `firedrake-preprocess-bibtex firedrake/src/firedrake/docs/source/_static/firedrake-apps.bib` passes.
- [x] `firedrake-preprocess-bibtex --validate firedrake/src/firedrake/docs/source/_static/firedrake-apps.bib`

### CODE REVIEW

**Comment by alexanderzimmerman** [comment]
@wence- , I ran `firedrake-preprocess-bibtex` within a Docker container from Firedrake's master Docker image, targeting the `firedrake-apps-bib` file in a clone of this PR's branch.

There was no output. So there aren't any errors; but I don't know what was expected exactly. I am now looking at [the script](https://github.com/firedrakeproject/firedrake/blob/master/scripts/firedrake-preprocess-bibtex) to see where output might have gone.

**Comment by alexanderzimmerman** [comment]
Should I see any output? Here is what I see:

```
firedrake@ff9cb9954d12:~$ source firedrake/bin/activate
(firedrake) firedrake@ff9cb9954d12:~$ python3 ./firedrake/bin/firedrake-preprocess-bibtex local/firedrake-apps.bib
(firedrake) firedrake@ff9cb9954d12:~$
```

**Comment by dham** [comment]
You don't expect output. It's basically a linter so it silently succeeds if there is nothing wrong and dies noisily if there is a problem.

**Comment by alexanderzimmerman** [comment]
> You don't expect output. It's basically a linter so it silently succeeds if there is nothing wrong and dies noisily if there is a problem.

Alright, then I'm calling this ready. Thanks!

**Comment by wence-** [comment]
> Alright, then I'm calling this ready. Thanks!

According to https://jenkins.ese.ic.ac.uk/blue/organizations/jenkins/firedrake/detail/PR-1994/1/pipeline, this failed the validation. Can you try running in `--validate` mode locally? Thanks!

**Comment by alexanderzimmerman** [comment]
I see the same (no output) with the `--validate` flag:

    (firedrake) firedrake@db251337b045:~$ python3 ./firedrake/bin/firedrake-preprocess-bibtex --validate local/firedrake-apps.bib
    (firedrake) firedrake@db251337b045:~$

**Comment by alexanderzimmerman** [comment]
[The error on Jenkins](https://jenkins.ese.ic.ac.uk/blue/organizations/jenkins/firedrake/detail/PR-1994/1/pipeline) says

    firedrake/src/firedrake/docs/source/_static/firedrake-apps.bib would be changed by firedrake-preprocess-bibtex. Please preprocess it and commit the result
    
   Which leads me to believe that `firedrake-preprocess-bibtex` was supposed to modify `firedrake-apps.bib` and that I am supposed to commit the modified file. So far I understood that I was supposed to run the preprocess (with or without `--validate`) *after* committing the file, i.e. not expecting any changes to it that were supposed to be committed.

**Comment by alexanderzimmerman** [comment]
Yeah, here is the diff after running the preprocessor:

    $ git diff
    diff --git a/docs/source/_static/firedrake-apps.bib b/docs/source/_static/firedrake-apps.bib
    index 22750720..021d9b81 100644
    --- a/docs/source/_static/firedrake-apps.bib
    +++ b/docs/source/_static/firedrake-apps.bib
    @@ -1074,13 +1074,14 @@ firedrake-preprocess-bibtex firedrake-apps.bib
     }
    
     @article{Zimmerman2021,
    -  author = {Zimmerman, Alexander G. and Kowalski, Julia},
    -  journal = {Computers & Mathematics with Applications},
    -  volume = {84},
    -  pages = {77-96},
    -  issn = {0898-1221},
    -  doi = {https://doi.org/10.1016/j.camwa.2020.11.008},
    -  title = {Mixed finite elements for convection-coupled phase-change in enthalpy form: Open software verified and applied to 2D benchmarks},
    -  url = {https://www.sciencedirect.com/science/article/pii/S0898122120304338},
    -  year = {2021}
    +  author       = {Zimmerman, Alexander G. and Kowalski, Julia},
    +  doi          = {https://doi.org/10.1016/j.camwa.2020.11.008},
    +  issn         = {0898-1221},
    +  journal      = {Computers & Mathematics with Applications},
    +  pages        = {77-96},
    +  title        = {Mixed finite elements for convection-coupled phase-change in enthalpy form: Open software verified and applied to 2D benchmarks},
    +  url          = {https://www.sciencedirect.com/science/article/pii/S0898122120304338},
    +  volume       = {84},
    +  year         = {2021}
     }

**Comment by alexanderzimmerman** [comment]
@wence- for now I assumed that I was supposed to commit the modified file and did that now, so we'll see what Jenkins says.

**Comment by alexanderzimmerman** [comment]
I don't know if that was the intended workflow in the end, but Jenkins is happy. Also will #1996 automate this for next time?

**Review by wence- — APPROVED** [review]

**Comment by wence-** [comment]
> I don't know if that was the intended workflow in the end, but Jenkins is happy. Also will #1996 automate this for next time?

Thanks. It won't, but you will notice the failure quicker.

**Comment by alexanderzimmerman** [comment]
Thanks @wence- !

**Pull request merged**
