### PR TITLE
Tsslac version1.1 optimisation

### PR DESCRIPTION
**Pull request by narciuch**
Remove ComponentTensors in GEM DAG which results in fewer unnecessary temporaries being created in Slate. 

Note that as of the recent merge with tsslac_version1.1, an AssertionError has appeared when running test_blocks() and test_layers(). The error is 
```
in replace_indices_flexiblyindexed
    assert isinstance(child, Terminal)
```

### CODE REVIEW

**Comment by miklos1** [comment]
> an AssertionError has appeared

So what type is that non-terminal that is being flexibly indexed?

**Comment by sv2518** [comment]
> Note that as of the recent merge with tsslac_version1.1, an AssertionError has appeared when running test_blocks() and test_layers(). The error is
> 
> ```
> in replace_indices_flexiblyindexed
>     assert isinstance(child, Terminal)
> ```
I use FlexiblyIndexed nodes to generate Indexed things with offsets for the translation Slate blocks, so FlexiblyIndexed do not solely act on Terminals anymore. Just remove the assertion.

**Comment by narciuch** [comment]
Removing this outdated assertion works to fix this issue.
@sv2518 will remove this assertion in the translation-of-comptensors branch in tsfc

**Comment by miklos1** [comment]
Just for your information: originally, I only used `FlexiblyIndexed` for indexing input and output buffers with views and shapes.  That's why the assertion is the way it is.  You can, of course, extend this, but you also have to take care of correct code generation for those new cases.

**Comment by sv2518** [comment]
Do you still want me to merge this or can we close this, @narciuch ?

**Pull request merged**
