### PR TITLE
Wence/feature patch facets

### PR DESCRIPTION
**Pull request by wence-**
Implement interior face terms for PCPatch. Will need a PETSc PR which is currently open.

### CODE REVIEW

**Comment by wence-** [comment]
Rebased and squashed all of this. Need to merge the petscp4y change and update the firedrake petsc pointer I think.

**Comment by wence-** [comment]
OK, this needs https://bitbucket.org/petsc/petsc/pull-requests/1459/fix-semantics-of-patch-callback-functions/diff, hopefully that is all now.

**Comment by dham** [comment]
Should I be worried about the fact that this passes tests despite the fact that the upstream change hasn't landed yet? Looks like a hole in coverage.

**Comment by wence-** [comment]
No, because it had edited the branch of petsc we were testing with.

**Pull request merged**
