### PR TITLE
Add petsc4py to firedrake-update package list

### PR DESCRIPTION
**Pull request by connorjward**
This is essentially the same as #2065 but fixes `firedrake-update`.

### CODE REVIEW

**Comment by sv2518** [comment]
I have just cherry-picked this into #2038. In that PR I also added firedrake-update before we build the docs, but the firedrake-update is failing. You can see the failure if you click on the failed action of the doc build int that PR. Maybe I am missing something, but maybe this is not a sufficient fix.

**Comment by sv2518** [comment]
Ah no, actually I understand why it doesn't work on my PR. Cherry-picking is insufficient for me there because I think the firedrake-update that I have added into the actions of the docs build runs basically on the master branch. This should work for me as soon as it is merged.

**Comment by wence-** [comment]
> I have just cherry-picked this into #2038. In that PR I also added firedrake-update before we build the docs, but the firedrake-update is failing. You can see the failure if you click on the failed action of the doc build int that PR. Maybe I am missing something, but maybe this is not a sufficient fix.

Can you run `firedrake-status` in that workflow to see if the commit is there? You can probably replicate more quickly by running the sequence of docker commands and just doing stuff "by hand".

**Comment by wence-** [comment]
firedrake-update is meant to update itself to the branch it's running on, I think.

**Comment by connorjward** [comment]
> firedrake-update is meant to update itself to the branch it's running on, I think.

I think for the docs build this may not be right. We are using the vanilla Docker container so Firedrake is installed into `/home/firedrake/firedrake`. It's possible that `firedrake-update` is using the Firedrake installed there (master) instead of the one we are testing.

**Comment by wence-** [comment]
> > firedrake-update is meant to update itself to the branch it's running on, I think.
> 
> I think for the docs build this may not be right. We are using the vanilla Docker container so Firedrake is installed into `/home/firedrake/firedrake`. It's possible that `firedrake-update` is using the Firedrake installed there (master) instead of the one we are testing.

Oh that's probably right. We should figure out how to do this properly...

**Comment by ksagiyam** [comment]
Looks to me `petsc4py` is again removed from the list at l.1677: `packages.remove("petsc4py")`?

**Comment by connorjward** [comment]
> Looks to me petsc4py is again removed from the list at l.1677: packages.remove("petsc4py")?

Good spot. This is a redundant thing to do. However, I think it could possibly be argued that including `"petsc4py"` inside of the `packages` list makes some sense even if we do nothing with it? It is a dependency so we should make it clear that that is the case?

**Comment by connorjward** [comment]
This is an important fix. Can it get merged ASAP?

**Comment by wence-** [comment]
Thanks!

**Pull request merged**
