### PR TITLE
solvers: Add more extensive error checking of arguments

### PR DESCRIPTION
**Pull request by wence-**
Validate not only that arguments to solve calls have the correct type,
but also the correct value (e.g. the LHS of a linear variational solve
must be a bilinear form).  This results in much easier to understand
error messages if the user does the wrong thing and accidentally
provides (say) a residual on the LHS of a linear variational solve, or
similar.

### CODE REVIEW

**Comment by miklos1** [comment]
Looks good.

**Comment by wence-** [comment]
This breaks firedrake-adjoint :).  Fixed by this change https://bitbucket.org/dolfin-adjoint/dolfin-adjoint/pull-requests/7/adjlinalg-dont-pass-a-vector-to-firedrakes/diff

**Comment by wence-** [comment]
OK, that change has landed, let's just check everything is working.

**Comment by miklos1** [comment]
An idea for even more checking and safety against PEBKAC:
> 17:27 < amcrae1> I'd used a NonlinearVariationalProblem, but a LinearVariationalSolver

which caused SNES to stop after 1 iteration.

**Pull request merged**
