### PR TITLE
add some tests for the PyOP2 extruded VFS facet map bug

### PR DESCRIPTION
**Pull request by dorugeber**
Can be un-xfailed after OP2/PyOP2#447 lands.

### CODE REVIEW

**Comment by wence-** [comment]
So I think it's all fine, but care to add some restricted mass matrix integrals on the minimum-sized mesh for a `dS_h` a la test_bilinear_interior_facet_integral (in regression/test_facets.py)?

**Comment by wence-** [comment]
Particularly interesting would be combination of test function from VFS DG0 + trial function from (say) RT0 (because then the matrix blocks are not square).

**Comment by wence-** [comment]
FWIW, I think these work too.

**Comment by wence-** [comment]
PyOP2 fix is in, so tests can be unxfailed.

**Comment by dorugeber** [comment]
Added LHS tests, mixed and non-mixed, and rebased.  Over and out.

**Comment by wence-** [comment]
Yep, thanks, will merge.

**Pull request merged**
